#!/usr/bin/env python3
"""Expand biomarker_reference.json with ~100 new biomarkers from the Excel input report."""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'reference')
REF_FILE = os.path.join(DATA_DIR, 'biomarker_reference.json')

NEW_BIOMARKERS = [
    # === Advanced Lipid Panel ===
    {"id": "lipids_sdldl", "name": "Small Dense LDL Particles", "unit": "nmol/L", "category": "Lipids",
     "ref_range_min": None, "ref_range_max": 527.0,
     "text_chunk": "Small dense LDL (sdLDL) particles are a subfraction of LDL cholesterol that are more atherogenic due to increased arterial wall penetration, greater oxidative susceptibility, and prolonged circulation time. Measured by NMR spectroscopy (LipoProfile). Values above 527 nmol/L indicate Pattern B (small, dense) phenotype with increased cardiovascular risk independent of total LDL-C. sdLDL is particularly elevated in metabolic syndrome, insulin resistance, and hypertriglyceridemia. Optimal levels below 400 nmol/L are associated with reduced coronary event risk.",
     "clinical_significance": "More atherogenic LDL subfraction; elevated in metabolic syndrome and insulin resistance; independent CV risk predictor beyond LDL-C.",
     "epigenetic_clock": None, "genetic_modifiers": "APOB,CETP,LPL"},
    {"id": "lipids_ldl_size", "name": "LDL Particle Size", "unit": "nm", "category": "Lipids",
     "ref_range_min": 20.5, "ref_range_max": None,
     "text_chunk": "LDL particle size (peak diameter) measured by NMR spectroscopy distinguishes Pattern A (large buoyant, >20.5 nm) from Pattern B (small dense, <20.5 nm). Pattern B is associated with 3x increased coronary heart disease risk. Particle size is influenced by triglyceride metabolism, insulin resistance, and CETP activity. Optimal size above 21 nm indicates predominantly large buoyant LDL with lower atherogenic potential.",
     "clinical_significance": "Pattern B (small dense, <20.5 nm) carries 3x CHD risk vs Pattern A (large buoyant); modifiable through triglyceride reduction.",
     "epigenetic_clock": None, "genetic_modifiers": "CETP,LPL,APOC3"},
    {"id": "lipids_hdl_p", "name": "HDL Particle Number", "unit": "umol/L", "category": "Lipids",
     "ref_range_min": 30.5, "ref_range_max": None,
     "text_chunk": "HDL particle number (HDL-P) measured by NMR spectroscopy quantifies the concentration of HDL particles independent of cholesterol content. HDL-P may be a better predictor of cardiovascular risk than HDL cholesterol (HDL-C) because it reflects reverse cholesterol transport capacity. Low HDL-P with normal HDL-C suggests dysfunctional HDL with reduced atheroprotection. Optimal HDL-P above 35 umol/L is associated with reduced cardiovascular events.",
     "clinical_significance": "Better CV risk predictor than HDL-C alone; low HDL-P with normal HDL-C indicates dysfunctional HDL particles.",
     "epigenetic_clock": None, "genetic_modifiers": "ABCA1,LCAT,CETP"},
    {"id": "lipids_large_hdl", "name": "Large HDL Particles", "unit": "umol/L", "category": "Lipids",
     "ref_range_min": 4.8, "ref_range_max": None,
     "text_chunk": "Large HDL particles are the subfraction most associated with effective reverse cholesterol transport and atheroprotection. Measured by NMR spectroscopy. Higher levels of large HDL indicate mature, cholesterol-laden particles actively removing cholesterol from arterial walls. Optimal levels above 7 umol/L. Low large HDL with elevated small HDL suggests impaired HDL maturation, often seen with CETP variants or metabolic syndrome.",
     "clinical_significance": "Most atheroprotective HDL subfraction; reflects effective reverse cholesterol transport capacity.",
     "epigenetic_clock": None, "genetic_modifiers": "CETP,ABCA1,LCAT"},
    {"id": "lipids_large_vldl", "name": "Large VLDL Particles", "unit": "nmol/L", "category": "Lipids",
     "ref_range_min": None, "ref_range_max": 2.7,
     "text_chunk": "Large VLDL particles are triglyceride-rich lipoproteins secreted by the liver. Elevated large VLDL indicates hepatic triglyceride overproduction, a hallmark of insulin resistance and metabolic syndrome. Measured by NMR spectroscopy. Values above 2.7 nmol/L are associated with increased cardiovascular risk and atherogenic dyslipidemia. Large VLDL drives the formation of small dense LDL through lipoprotein remodeling. Optimal levels below 1.5 nmol/L.",
     "clinical_significance": "Marker of hepatic triglyceride overproduction; drives formation of atherogenic small dense LDL particles.",
     "epigenetic_clock": None, "genetic_modifiers": "APOC3,GCKR,PNPLA3"},
    {"id": "lipids_oxldl", "name": "Oxidized LDL", "unit": "U/L", "category": "Lipids",
     "ref_range_min": None, "ref_range_max": 60.0,
     "text_chunk": "Oxidized LDL (OxLDL) is a modified form of LDL that is a key initiator of atherosclerosis. OxLDL is taken up by macrophage scavenger receptors, forming foam cells in the arterial wall. Measured by ELISA. Elevated OxLDL indicates increased oxidative stress and atherogenic activity independent of LDL-C levels. Optimal levels below 50 U/L. Antioxidant intake (vitamin E, polyphenols) and statin therapy can reduce OxLDL.",
     "clinical_significance": "Key initiator of atherosclerosis through foam cell formation; reflects oxidative stress and atherogenic activity beyond LDL-C.",
     "epigenetic_clock": None, "genetic_modifiers": "PON1,MPO,SOD2"},
    {"id": "lipids_remnant_chol", "name": "Remnant Cholesterol", "unit": "mg/dL", "category": "Lipids",
     "ref_range_min": None, "ref_range_max": 24.0,
     "text_chunk": "Remnant cholesterol represents cholesterol carried by triglyceride-rich remnant lipoproteins (VLDL remnants and IDL). Calculated as Total Cholesterol minus LDL minus HDL. Elevated remnant cholesterol is an independent causal risk factor for coronary heart disease and all-cause mortality, as demonstrated by Mendelian randomization studies. Optimal levels below 18 mg/dL. Remnant cholesterol captures atherogenic risk missed by LDL-C alone.",
     "clinical_significance": "Causal risk factor for CHD per Mendelian randomization; captures atherogenic risk not reflected in LDL-C alone.",
     "epigenetic_clock": None, "genetic_modifiers": "APOC3,LPL,APOA5"},
    {"id": "lipids_ceramides", "name": "Ceramides Score", "unit": "score", "category": "Lipids",
     "ref_range_min": None, "ref_range_max": 6.0,
     "text_chunk": "The ceramide risk score (1-12 scale) is based on plasma concentrations of specific ceramide species (Cer16:0, Cer18:0, Cer24:1) and their ratios. Ceramides are bioactive sphingolipids that promote inflammation, apoptosis, and insulin resistance in arterial walls. Measured by LC-MS/MS. Scores above 6 indicate high cardiovascular risk. The ceramide score predicts major adverse cardiovascular events independently of LDL-C and other traditional risk factors.",
     "clinical_significance": "Novel CV risk biomarker based on sphingolipid species; predicts MACE independently of traditional lipid markers.",
     "epigenetic_clock": None, "genetic_modifiers": "SMPD1,CERS2"},

    # === Heart & Metabolic Extended ===
    {"id": "cardiac_mpo", "name": "Myeloperoxidase", "unit": "pmol/L", "category": "Cardiac",
     "ref_range_min": None, "ref_range_max": 470.0,
     "text_chunk": "Myeloperoxidase (MPO) is a heme peroxidase enzyme released by activated neutrophils and monocytes during inflammation. Elevated MPO indicates vascular inflammation and oxidative stress in the arterial wall, promoting LDL oxidation and endothelial dysfunction. MPO is an independent predictor of major adverse cardiac events (MACE) even in troponin-negative chest pain patients. Measured by ELISA from EDTA plasma. Optimal levels below 350 pmol/L.",
     "clinical_significance": "Vascular inflammation marker; predicts MACE in troponin-negative ACS; promotes LDL oxidation and endothelial dysfunction.",
     "epigenetic_clock": None, "genetic_modifiers": "MPO"},
    {"id": "cardiac_galectin3", "name": "Galectin-3", "unit": "ng/mL", "category": "Cardiac",
     "ref_range_min": None, "ref_range_max": 17.8,
     "text_chunk": "Galectin-3 is a beta-galactoside-binding lectin that drives cardiac fibrosis and remodeling. Elevated galectin-3 predicts heart failure hospitalization and mortality. FDA-cleared as a prognostic biomarker for heart failure alongside NT-proBNP. Measured by ELISA. Values above 17.8 ng/mL indicate increased risk of cardiac fibrosis and adverse outcomes. Useful for risk stratification in patients with established or suspected heart failure.",
     "clinical_significance": "FDA-cleared HF prognostic marker; drives cardiac fibrosis; predicts HF hospitalization and mortality alongside NT-proBNP.",
     "epigenetic_clock": None, "genetic_modifiers": "LGALS3"},
    {"id": "cardiac_tmao", "name": "TMAO", "unit": "uM", "category": "Cardiac",
     "ref_range_min": None, "ref_range_max": 6.2,
     "text_chunk": "Trimethylamine N-oxide (TMAO) is a gut microbiome-derived metabolite produced from dietary choline, carnitine, and betaine. Elevated TMAO promotes atherosclerosis through enhanced macrophage cholesterol accumulation, platelet hyperreactivity, and impaired reverse cholesterol transport. Measured by LC-MS/MS with stable isotope dilution. TMAO levels above 6.2 uM are associated with increased MACE risk. Dietary modification (reducing red meat, L-carnitine) and gut microbiome interventions can lower TMAO.",
     "clinical_significance": "Gut microbiome metabolite promoting atherosclerosis; modifiable through diet and microbiome interventions.",
     "epigenetic_clock": None, "genetic_modifiers": "FMO3"},
    {"id": "cardiac_adma", "name": "ADMA", "unit": "umol/L", "category": "Cardiac",
     "ref_range_min": 0.26, "ref_range_max": 0.64,
     "text_chunk": "Asymmetric dimethylarginine (ADMA) is an endogenous inhibitor of nitric oxide synthase (NOS). Elevated ADMA reduces NO bioavailability, causing endothelial dysfunction, vasoconstriction, and increased cardiovascular risk. ADMA is cleared by the enzyme DDAH and by renal excretion. Measured by LC-MS/MS from EDTA plasma. Levels above 0.64 umol/L predict cardiovascular events and all-cause mortality. Optimal range 0.30-0.55 umol/L. Exercise and dietary antioxidants may help reduce ADMA.",
     "clinical_significance": "Endogenous NOS inhibitor causing endothelial dysfunction; predicts CV events and mortality; reduced by exercise.",
     "epigenetic_clock": None, "genetic_modifiers": "DDAH1,DDAH2"},
    {"id": "cardiac_f2_isoprostanes", "name": "F2-Isoprostanes", "unit": "ng/mg Cr", "category": "Cardiac",
     "ref_range_min": None, "ref_range_max": 0.86,
     "text_chunk": "F2-Isoprostanes (8-iso-PGF2alpha) are prostaglandin-like compounds formed by free radical-catalyzed peroxidation of arachidonic acid. They are the gold standard biomarker of in vivo oxidative stress. Measured by LC-MS/MS from urine (normalized to creatinine). Elevated F2-isoprostanes indicate systemic oxidative damage and are associated with atherosclerosis, diabetes complications, and neurodegeneration. Optimal levels below 0.5 ng/mg Cr. Antioxidant supplementation and smoking cessation can reduce levels.",
     "clinical_significance": "Gold standard oxidative stress biomarker; elevated in atherosclerosis, diabetes complications, and neurodegeneration.",
     "epigenetic_clock": None, "genetic_modifiers": "SOD2,GPX1,CAT"},
    {"id": "cardiac_lppla2_activity", "name": "Lp-PLA2 Activity", "unit": "nmol/min/mL", "category": "Cardiac",
     "ref_range_min": None, "ref_range_max": 200.0,
     "text_chunk": "Lipoprotein-associated phospholipase A2 (Lp-PLA2) activity (PLAC test) measures the enzymatic activity of PLA2G7 bound to LDL particles. Lp-PLA2 generates pro-inflammatory mediators (lysophosphatidylcholine, oxidized fatty acids) within the arterial intima, promoting plaque instability. FDA-cleared as a cardiovascular risk marker. Activity above 200 nmol/min/mL indicates increased risk of coronary events and stroke. Optimal below 150 nmol/min/mL. Statin therapy reduces Lp-PLA2 activity.",
     "clinical_significance": "FDA-cleared CV risk marker; promotes arterial plaque instability; reduced by statin therapy.",
     "epigenetic_clock": None, "genetic_modifiers": "PLA2G7"},
    {"id": "cardiac_glyca", "name": "GlycA", "unit": "umol/L", "category": "Cardiac",
     "ref_range_min": None, "ref_range_max": 400.0,
     "text_chunk": "GlycA (glycoprotein acetylation) is a composite NMR-measured biomarker reflecting the glycosylation state of acute phase proteins (alpha-1 acid glycoprotein, haptoglobin, alpha-1 antitrypsin, transferrin, alpha-2 macroglobulin). GlycA integrates systemic inflammation from multiple pathways into a single measurement. Elevated GlycA predicts cardiovascular events, type 2 diabetes, and all-cause mortality independently of hs-CRP. Optimal levels below 350 umol/L. GlycA is more stable than hs-CRP (less day-to-day variation).",
     "clinical_significance": "Composite inflammation marker more stable than hs-CRP; predicts CV events, T2D, and mortality independently.",
     "epigenetic_clock": None, "genetic_modifiers": ""},

    # === Metabolic Extended ===
    {"id": "metabolic_ldh", "name": "Lactate Dehydrogenase", "unit": "IU/L", "category": "CMP",
     "ref_range_min": 120.0, "ref_range_max": 246.0,
     "text_chunk": "Lactate dehydrogenase (LDH) is an intracellular enzyme present in virtually all tissues. Elevated LDH indicates tissue damage or cell turnover from any cause: hemolysis, liver disease, myocardial infarction, malignancy, pulmonary embolism, or muscle injury. LDH isoenzyme fractionation can help localize the source. Measured by spectrophotometry (IFCC kinetic UV method). Normal range 120-246 IU/L, optimal below 200 IU/L. LDH is used in tumor staging (lymphoma, testicular cancer) and as a hemolysis marker.",
     "clinical_significance": "Non-specific tissue damage marker; elevated in hemolysis, liver disease, MI, malignancy; used in tumor staging.",
     "epigenetic_clock": None, "genetic_modifiers": ""},

    # === Autoimmunity (30 new) ===
    {"id": "autoimmune_ana_screen", "name": "ANA Screen", "unit": "", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Antinuclear antibody (ANA) screen detects autoantibodies directed against nuclear components. Performed by indirect immunofluorescence (IIF) on HEp-2 cells. Positive ANA is found in systemic lupus erythematosus (SLE, >95%), drug-induced lupus, Sjogren syndrome, scleroderma, and mixed connective tissue disease. However, low-titer ANA positivity occurs in 5-15% of healthy individuals, especially elderly women. Negative ANA effectively excludes SLE (high negative predictive value). Positive results require titer and pattern characterization.",
     "clinical_significance": "Screening test for systemic autoimmune diseases; negative ANA effectively excludes SLE; positive in 5-15% of healthy individuals.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DR2,HLA-DR3"},
    {"id": "autoimmune_ana_titer", "name": "ANA Titer", "unit": "titer", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "ANA titer quantifies the highest serum dilution at which antinuclear antibodies remain detectable. Higher titers (>=1:160) have greater specificity for autoimmune disease. Titers of 1:40 are common in healthy individuals (up to 32%) and are not clinically significant. Titers >=1:640 are strongly suggestive of systemic autoimmune disease. Serial titer monitoring does not reliably correlate with disease activity in SLE. Titer should always be interpreted alongside ANA pattern and clinical presentation.",
     "clinical_significance": "Higher titers (>=1:160) more specific for autoimmune disease; 1:40 common in healthy individuals; serial monitoring not recommended.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_ana_pattern", "name": "ANA Pattern", "unit": "", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "ANA pattern (immunofluorescence staining pattern on HEp-2 cells) helps identify the target autoantigen and guides specific antibody testing. Homogeneous pattern suggests anti-dsDNA or anti-histone (SLE, drug-induced lupus). Speckled pattern suggests anti-Sm, anti-RNP, anti-SSA/Ro, anti-SSB/La. Centromere pattern is characteristic of limited scleroderma (CREST). Nucleolar pattern suggests anti-Scl-70 (diffuse scleroderma). Pattern identification directs subsequent reflex testing.",
     "clinical_significance": "Directs specific autoantibody testing; homogeneous suggests SLE, speckled suggests mixed CTD, centromere suggests limited scleroderma.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_rf", "name": "Rheumatoid Factor", "unit": "IU/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 13.9,
     "text_chunk": "Rheumatoid factor (RF) is an autoantibody (typically IgM) directed against the Fc portion of IgG. Present in 70-80% of rheumatoid arthritis (RA) patients but also found in other autoimmune diseases, chronic infections, and 5-10% of healthy elderly. Measured by immunoturbidimetry. Higher titers correlate with more aggressive disease, extra-articular manifestations, and worse prognosis. RF combined with anti-CCP has improved diagnostic specificity for RA (>95%). Optimal below 10 IU/mL.",
     "clinical_significance": "Present in 70-80% of RA; also positive in other autoimmune diseases and healthy elderly; combined with anti-CCP improves RA specificity to >95%.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DRB1"},
    {"id": "autoimmune_anti_ccp", "name": "Anti-CCP", "unit": "U/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 19.9,
     "text_chunk": "Anti-cyclic citrullinated peptide (anti-CCP) antibodies are highly specific (>95%) for rheumatoid arthritis and can be detected years before clinical disease onset. Anti-CCP positivity predicts more aggressive, erosive disease course. Present in 60-70% of RA patients. Unlike RF, anti-CCP is rarely positive in other conditions. Measured by ELISA or chemiluminescent immunoassay. Values above 19.9 U/mL are positive. Anti-CCP is now included in the 2010 ACR/EULAR RA classification criteria.",
     "clinical_significance": "Highly specific for RA (>95%); predicts erosive disease; can be positive years before symptom onset; included in ACR/EULAR criteria.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DRB1,PTPN22"},
    {"id": "autoimmune_c3", "name": "C3 Complement", "unit": "mg/dL", "category": "Autoimmunity",
     "ref_range_min": 90.0, "ref_range_max": 180.0,
     "text_chunk": "Complement C3 is the central component of the complement cascade, involved in opsonization, inflammation, and immune complex clearance. Low C3 indicates complement consumption from active autoimmune disease (SLE flare, lupus nephritis), immune complex-mediated disease, or hereditary complement deficiency. High C3 occurs as an acute phase response. Measured by immunoturbidimetry. Serial monitoring helps track SLE disease activity (C3 drops before clinical flare). Optimal range 100-150 mg/dL.",
     "clinical_significance": "Low C3 indicates complement consumption in active SLE/lupus nephritis; serial monitoring tracks disease activity; drops before clinical flare.",
     "epigenetic_clock": None, "genetic_modifiers": "C3"},
    {"id": "autoimmune_c4", "name": "C4 Complement", "unit": "mg/dL", "category": "Autoimmunity",
     "ref_range_min": 10.0, "ref_range_max": 40.0,
     "text_chunk": "Complement C4 is consumed in the classical complement pathway activated by immune complexes. Low C4 is more sensitive than low C3 for detecting classical pathway activation in SLE. C4 null alleles (C4A or C4B deficiency) are common in SLE patients and cause constitutively low C4 independent of disease activity. Measured by immunoturbidimetry. Low C4 with normal C3 suggests early or mild classical pathway activation. Both low C3 and C4 indicate severe complement consumption. Optimal range 15-35 mg/dL.",
     "clinical_significance": "More sensitive than C3 for classical pathway activation; C4 null alleles common in SLE cause baseline low C4; both low C3/C4 indicates severe consumption.",
     "epigenetic_clock": None, "genetic_modifiers": "C4A,C4B"},
    {"id": "autoimmune_ch50", "name": "CH50 Total Complement", "unit": "U/mL", "category": "Autoimmunity",
     "ref_range_min": 31.0, "ref_range_max": 60.0,
     "text_chunk": "CH50 (total hemolytic complement) is a functional assay measuring the entire classical complement pathway (C1 through C9). A normal CH50 excludes complete deficiency of any classical pathway component. Low CH50 occurs in active SLE, serum sickness, cryoglobulinemia, or hereditary complement deficiencies. Near-zero CH50 strongly suggests complete deficiency of a complement component. Measured by hemolytic (liposome) assay. Optimal range 35-55 U/mL.",
     "clinical_significance": "Functional screen of entire classical complement pathway; normal result excludes complete component deficiency; near-zero suggests hereditary deficiency.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_anti_dsdna", "name": "Anti-dsDNA Antibodies", "unit": "IU/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 9.9,
     "text_chunk": "Anti-double-stranded DNA (anti-dsDNA) antibodies are highly specific for systemic lupus erythematosus (specificity >95%) and correlate with disease activity, especially lupus nephritis. Rising anti-dsDNA titers often precede SLE flares by weeks to months. Measured by ELISA, Farr assay, or Crithidia luciliae immunofluorescence. Present in 60-70% of SLE patients. Anti-dsDNA combined with low complement (C3/C4) is a strong predictor of renal involvement. Optimal below 5 IU/mL in healthy individuals.",
     "clinical_significance": "Highly specific for SLE (>95%); correlates with disease activity and lupus nephritis; rising titers predict flares.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DR2,HLA-DR3"},
    {"id": "autoimmune_anti_smith", "name": "Anti-Smith Antibodies", "unit": "AI", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 1.0,
     "text_chunk": "Anti-Smith (anti-Sm) antibodies target small nuclear ribonucleoprotein (snRNP) and are pathognomonic for SLE (specificity ~99%). Present in only 20-30% of SLE patients but virtually absent in other conditions. Anti-Sm levels do not correlate well with disease activity. Positive anti-Sm is included in the SLICC classification criteria for SLE. Measured by ELISA or multiplex immunoassay. A positive result in the appropriate clinical context is virtually diagnostic of SLE.",
     "clinical_significance": "Pathognomonic for SLE (specificity ~99%); present in 20-30% of SLE patients; does not fluctuate with disease activity.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_anti_ssa", "name": "Anti-SSA/Ro Antibodies", "unit": "AI", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 1.0,
     "text_chunk": "Anti-SSA/Ro antibodies target Ro52 and Ro60 ribonucleoproteins. Present in Sjogren syndrome (60-70%), subacute cutaneous lupus, neonatal lupus, and SLE. Anti-SSA is the most common extractable nuclear antigen (ENA) antibody in autoimmune disease. Critical clinical significance in pregnancy: maternal anti-SSA can cross the placenta and cause congenital heart block in the fetus (1-2% risk per pregnancy). All anti-SSA-positive women of childbearing age require preconception counseling.",
     "clinical_significance": "Associated with Sjogren, SLE, neonatal lupus; critical pregnancy risk for congenital heart block (1-2%); requires preconception counseling.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DR3"},
    {"id": "autoimmune_anti_ssb", "name": "Anti-SSB/La Antibodies", "unit": "AI", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 1.0,
     "text_chunk": "Anti-SSB/La antibodies are almost always found in conjunction with anti-SSA/Ro and are highly specific for Sjogren syndrome. Isolated anti-SSB (without anti-SSA) is rare. Anti-SSB positivity in the context of anti-SSA may modulate neonatal lupus risk. Present in 40-50% of primary Sjogren syndrome and 10-15% of SLE patients. Measured by ELISA or multiplex immunoassay.",
     "clinical_significance": "Highly specific for Sjogren syndrome; almost always co-occurs with anti-SSA; may modulate neonatal lupus risk.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_anti_rnp", "name": "Anti-RNP Antibodies", "unit": "AI", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 1.0,
     "text_chunk": "Anti-U1 RNP antibodies target U1 small nuclear ribonucleoprotein. High-titer anti-RNP is the defining serological feature of mixed connective tissue disease (MCTD). Also found in SLE (25-47%), scleroderma, and polymyositis. Anti-RNP positivity in SLE is associated with lower risk of nephritis but higher risk of Raynaud phenomenon, arthritis, and interstitial lung disease. Measured by ELISA or multiplex immunoassay.",
     "clinical_significance": "Defining marker of MCTD at high titers; in SLE associated with lower nephritis risk but higher Raynaud/arthritis/ILD risk.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_anti_scl70", "name": "Anti-Scl-70 Antibodies", "unit": "AI", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 1.0,
     "text_chunk": "Anti-Scl-70 (anti-topoisomerase I) antibodies are specific for diffuse cutaneous systemic sclerosis (dcSSc). Present in 20-40% of dcSSc patients. Anti-Scl-70 positivity is associated with more severe skin involvement, pulmonary fibrosis (interstitial lung disease), and worse prognosis compared to anti-centromere antibody-positive limited scleroderma. Measured by ELISA or multiplex immunoassay.",
     "clinical_significance": "Specific for diffuse systemic sclerosis; associated with severe skin disease and pulmonary fibrosis; worse prognosis vs anti-centromere.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_anti_jo1", "name": "Anti-Jo-1 Antibodies", "unit": "AI", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 1.0,
     "text_chunk": "Anti-Jo-1 antibodies target histidyl-tRNA synthetase and are the most common of the anti-aminoacyl-tRNA synthetase (anti-ARS) antibodies. They define the antisynthetase syndrome: inflammatory myopathy, interstitial lung disease, arthritis, mechanic's hands, Raynaud phenomenon, and fever. Present in 20-30% of polymyositis/dermatomyositis patients. Anti-Jo-1 positivity strongly predicts interstitial lung disease. Measured by ELISA or multiplex immunoassay.",
     "clinical_significance": "Defines antisynthetase syndrome; strongly predicts interstitial lung disease in myositis patients; present in 20-30% of PM/DM.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_anti_centromere", "name": "Anti-Centromere Antibodies", "unit": "AI", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 1.0,
     "text_chunk": "Anti-centromere antibodies (ACA) target centromere proteins (CENP-A, CENP-B, CENP-C). Highly specific for limited cutaneous systemic sclerosis (CREST syndrome: calcinosis, Raynaud, esophageal dysmotility, sclerodactyly, telangiectasia). Present in 60-80% of limited SSc. ACA positivity is associated with better prognosis than anti-Scl-70 but carries increased risk of pulmonary arterial hypertension. Identified by characteristic centromere pattern on HEp-2 IIF.",
     "clinical_significance": "Highly specific for limited scleroderma (CREST); better prognosis than dcSSc but increased PAH risk.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_acl_igg", "name": "Anti-Cardiolipin IgG", "unit": "GPL U/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 14.9,
     "text_chunk": "Anti-cardiolipin IgG antibodies are part of the antiphospholipid antibody panel used to diagnose antiphospholipid syndrome (APS). APS causes arterial/venous thrombosis and pregnancy complications (recurrent miscarriage, preeclampsia, IUGR). Medium-to-high titer anti-cardiolipin IgG (>40 GPL) on 2 occasions 12 weeks apart is one of the laboratory criteria for APS. Measured by ELISA. Low-titer positivity may be transient and non-pathogenic.",
     "clinical_significance": "Part of APS diagnostic criteria; medium-high titers on 2 occasions predict thrombosis and pregnancy complications.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_acl_igm", "name": "Anti-Cardiolipin IgM", "unit": "MPL U/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 12.4,
     "text_chunk": "Anti-cardiolipin IgM antibodies are part of the antiphospholipid antibody panel. IgM isotype is less strongly associated with thrombotic risk compared to IgG but still part of the revised Sapporo APS classification criteria. Transient IgM positivity can occur with infections (syphilis, HIV, hepatitis C). Persistent medium-high titer IgM on 2 occasions 12 weeks apart supports APS diagnosis. Measured by ELISA.",
     "clinical_significance": "Part of APS panel; IgM less thrombotic risk than IgG; transient positivity possible with infections.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_b2gp1_igg", "name": "Anti-Beta-2 GP I IgG", "unit": "SGU", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 20.0,
     "text_chunk": "Anti-beta-2 glycoprotein I (anti-B2GP1) IgG antibodies target beta-2 glycoprotein I, a phospholipid-binding protein. Anti-B2GP1 is considered the most pathogenic antiphospholipid antibody, directly promoting thrombosis through endothelial activation, complement activation, and platelet aggregation. Part of the updated Sydney APS classification criteria. Measured by ELISA. Persistent positivity on 2 occasions 12 weeks apart is diagnostically significant.",
     "clinical_significance": "Most pathogenic antiphospholipid antibody; directly promotes thrombosis; part of updated APS classification criteria.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_b2gp1_igm", "name": "Anti-Beta-2 GP I IgM", "unit": "SMU", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 20.0,
     "text_chunk": "Anti-beta-2 glycoprotein I IgM is part of the complete antiphospholipid antibody panel. IgM isotype has weaker clinical associations with thrombosis compared to IgG but is included in diagnostic workup. Persistent positivity should prompt clinical correlation for APS features. Measured by ELISA. Values above 20 SMU are considered positive.",
     "clinical_significance": "Part of complete APS workup; IgM isotype has weaker thrombotic association than IgG.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_lupus_anticoag", "name": "Lupus Anticoagulant", "unit": "seconds", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 44.0,
     "text_chunk": "Lupus anticoagulant (LA) is detected by prolongation of phospholipid-dependent coagulation assays (dRVVT screen/confirm ratio). Despite the name, LA is a prothrombotic antibody that causes thrombosis in vivo but prolongs clotting time in vitro. LA is the strongest predictor of thrombosis among the antiphospholipid antibodies. Triple positivity (LA + anti-cardiolipin + anti-B2GP1) carries the highest thrombotic risk. LA testing requires no anticoagulant therapy at time of draw.",
     "clinical_significance": "Strongest thrombotic predictor among antiphospholipid antibodies; triple positivity carries highest risk; prothrombotic in vivo despite prolonged in vitro clotting.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_ttg_iga", "name": "tTG-IgA", "unit": "U/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 3.9,
     "text_chunk": "Anti-tissue transglutaminase IgA (tTG-IgA) is the preferred serologic screening test for celiac disease (sensitivity 93-98%, specificity 95-98%). Values above 10x the upper limit of normal are virtually diagnostic without biopsy (ESPGHAN criteria in children). Must be paired with total IgA to exclude IgA deficiency (2-3% of celiac patients are IgA-deficient, causing false-negative tTG-IgA). Measured by ELISA. Optimal below 3 U/mL.",
     "clinical_significance": "Preferred celiac disease screening test (93-98% sensitivity); must check total IgA to exclude deficiency; >10x ULN virtually diagnostic.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DQ2,HLA-DQ8"},
    {"id": "autoimmune_ttg_igg", "name": "tTG-IgG", "unit": "U/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 5.9,
     "text_chunk": "Anti-tissue transglutaminase IgG (tTG-IgG) is used for celiac disease screening in IgA-deficient patients (2-3% of celiac patients). Lower sensitivity and specificity than tTG-IgA in IgA-sufficient patients. Should only be ordered when total IgA is low or when tTG-IgA is negative with high clinical suspicion. Measured by ELISA.",
     "clinical_significance": "Used for celiac screening in IgA-deficient patients; lower accuracy than tTG-IgA in IgA-sufficient individuals.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DQ2,HLA-DQ8"},
    {"id": "autoimmune_iga_total", "name": "IgA Total", "unit": "mg/dL", "category": "Autoimmunity",
     "ref_range_min": 91.0, "ref_range_max": 414.0,
     "text_chunk": "Total immunoglobulin A (IgA) is the predominant antibody at mucosal surfaces (GI, respiratory, urogenital). Low IgA (selective IgA deficiency, prevalence 1:500) causes false-negative tTG-IgA in celiac screening and increases sinopulmonary infection risk. Elevated IgA occurs in IgA nephropathy, liver cirrhosis, chronic infections, and IgA myeloma. IgA deficiency is the most common primary immunodeficiency. Measured by immunoturbidimetry. Optimal 100-350 mg/dL.",
     "clinical_significance": "Must be measured with celiac screening to exclude IgA deficiency; low IgA is most common primary immunodeficiency (1:500).",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_ema_iga", "name": "EMA IgA", "unit": "", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Anti-endomysial antibodies IgA (EMA-IgA) are highly specific (>99%) for celiac disease. EMA targets tissue transglutaminase in the endomysium of smooth muscle. Detected by indirect immunofluorescence on monkey esophagus or human umbilical cord substrate. More labor-intensive and operator-dependent than tTG-IgA ELISA, so typically used as a confirmatory test. A positive EMA with positive tTG-IgA is essentially diagnostic of celiac disease.",
     "clinical_significance": "Highly specific (>99%) confirmatory test for celiac disease; positive EMA + tTG-IgA is essentially diagnostic.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DQ2,HLA-DQ8"},
    {"id": "autoimmune_dgp_iga", "name": "DGP-IgA", "unit": "U", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 19.9,
     "text_chunk": "Deamidated gliadin peptide IgA (DGP-IgA) detects antibodies against deamidated gluten peptides. Useful as an additional celiac marker, particularly in children under 2 years where tTG-IgA may be less reliable. DGP-IgA has good sensitivity (80-95%) and specificity (90-95%) for celiac disease. Measured by ELISA.",
     "clinical_significance": "Additional celiac marker; particularly useful in children under 2 years; good sensitivity and specificity.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DQ2,HLA-DQ8"},
    {"id": "autoimmune_dgp_igg", "name": "DGP-IgG", "unit": "U", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 19.9,
     "text_chunk": "Deamidated gliadin peptide IgG (DGP-IgG) is used for celiac disease screening in IgA-deficient patients as an alternative to tTG-IgG. DGP-IgG has better specificity than older gliadin antibody assays. Useful when total IgA is low and tTG-IgA may be falsely negative. Measured by ELISA.",
     "clinical_significance": "Alternative celiac marker for IgA-deficient patients; better specificity than older gliadin antibody assays.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DQ2,HLA-DQ8"},
    {"id": "autoimmune_ama", "name": "Anti-Mitochondrial Antibodies", "unit": "Units", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 20.0,
     "text_chunk": "Anti-mitochondrial antibodies (AMA) target the E2 subunit of pyruvate dehydrogenase complex on the inner mitochondrial membrane. AMA is the serological hallmark of primary biliary cholangitis (PBC), present in >90% of patients with >95% specificity. AMA can be detected years before clinical disease or elevated ALP. Measured by indirect immunofluorescence or ELISA. Positive AMA with elevated ALP is virtually diagnostic of PBC without liver biopsy.",
     "clinical_significance": "Pathognomonic for primary biliary cholangitis (>90% sensitivity, >95% specificity); can precede clinical disease by years.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_asma", "name": "Anti-Smooth Muscle Antibodies", "unit": "titer", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Anti-smooth muscle antibodies (ASMA) target F-actin and are associated with autoimmune hepatitis type 1 (AIH-1). Present in 70-80% of AIH-1 patients. Titers >=1:80 are clinically significant. ASMA can also be positive in chronic viral hepatitis, primary sclerosing cholangitis, and other liver diseases at lower titers. Measured by indirect immunofluorescence. ASMA combined with ANA and elevated IgG supports AIH-1 diagnosis.",
     "clinical_significance": "Associated with autoimmune hepatitis type 1 (70-80%); titers >=1:80 are clinically significant; combined with ANA and IgG supports AIH diagnosis.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_igg_total", "name": "IgG Total", "unit": "mg/dL", "category": "Autoimmunity",
     "ref_range_min": 694.0, "ref_range_max": 1618.0,
     "text_chunk": "Total immunoglobulin G (IgG) is the most abundant serum antibody. Elevated IgG occurs in autoimmune hepatitis (>1.5x ULN is part of diagnostic criteria), chronic infections, liver cirrhosis, IgG4-related disease, and IgG myeloma. Low IgG indicates primary or secondary immunodeficiency. IgG subclass analysis (IgG1-4) may be needed for suspected IgG4-related disease or selective subclass deficiency. Measured by immunoturbidimetry. Optimal 750-1400 mg/dL.",
     "clinical_significance": "Elevated in autoimmune hepatitis (diagnostic criterion), chronic infections, cirrhosis; low indicates immunodeficiency.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_igm_total", "name": "IgM Total", "unit": "mg/dL", "category": "Autoimmunity",
     "ref_range_min": 40.0, "ref_range_max": 230.0,
     "text_chunk": "Total immunoglobulin M (IgM) is the first antibody produced in acute immune response and predominates in primary biliary cholangitis (PBC), where polyclonal IgM elevation is characteristic. Elevated IgM also occurs in Waldenstrom macroglobulinemia (monoclonal IgM), chronic infections, and hyper-IgM syndrome. Low IgM increases susceptibility to encapsulated bacterial infections. Measured by immunoturbidimetry. Optimal 50-200 mg/dL.",
     "clinical_significance": "Characteristically elevated in PBC; monoclonal IgM in Waldenstrom macroglobulinemia; low increases encapsulated bacterial infection risk.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "autoimmune_ige_total", "name": "IgE Total", "unit": "IU/mL", "category": "Autoimmunity",
     "ref_range_min": None, "ref_range_max": 114.0,
     "text_chunk": "Total immunoglobulin E (IgE) mediates type I (immediate) hypersensitivity reactions. Elevated total IgE occurs in allergic diseases (atopic dermatitis, allergic rhinitis, asthma), parasitic infections, allergic bronchopulmonary aspergillosis (ABPA), and hyper-IgE syndrome. Very high IgE (>2000 IU/mL) suggests ABPA or hyper-IgE syndrome. Specific IgE testing (RAST/ImmunoCAP) identifies individual allergens. Measured by chemiluminescent immunoassay. Optimal below 80 IU/mL.",
     "clinical_significance": "Elevated in atopic diseases, parasitic infections, ABPA; very high levels suggest ABPA or hyper-IgE syndrome; specific IgE identifies individual allergens.",
     "epigenetic_clock": None, "genetic_modifiers": "IL4,IL13"},

    # === Immune ===
    {"id": "immune_cd4", "name": "CD4+ T Cells", "unit": "cells/uL", "category": "Immune",
     "ref_range_min": 490.0, "ref_range_max": 1740.0,
     "text_chunk": "CD4+ T cells (helper T lymphocytes) orchestrate adaptive immune responses through cytokine secretion and immune cell activation. CD4 count is the primary marker for monitoring HIV disease progression and ART response. CD4 below 200 cells/uL defines AIDS and triggers opportunistic infection prophylaxis. In non-HIV contexts, low CD4 occurs in idiopathic CD4 lymphopenia, immunosuppressive therapy, and some autoimmune diseases. Measured by flow cytometry (CD3+CD4+). Optimal 600-1500 cells/uL.",
     "clinical_significance": "Primary HIV monitoring marker; <200 defines AIDS; also relevant in immunosuppression and autoimmune disease.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA"},
    {"id": "immune_cd8", "name": "CD8+ T Cells", "unit": "cells/uL", "category": "Immune",
     "ref_range_min": 180.0, "ref_range_max": 1170.0,
     "text_chunk": "CD8+ T cells (cytotoxic T lymphocytes) kill virus-infected cells and tumor cells through perforin/granzyme-mediated cytotoxicity. Elevated CD8 occurs in acute viral infections (CMV, EBV, HIV), chronic viral hepatitis, and some autoimmune conditions. Low CD8 is seen in some primary immunodeficiencies. The CD4/CD8 ratio provides additional immune balance information. Measured by flow cytometry (CD3+CD8+). Optimal 250-1000 cells/uL.",
     "clinical_significance": "Cytotoxic lymphocytes; elevated in viral infections; important for immune balance assessment via CD4/CD8 ratio.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA"},
    {"id": "immune_cd4_cd8_ratio", "name": "CD4/CD8 Ratio", "unit": "ratio", "category": "Immune",
     "ref_range_min": 0.9, "ref_range_max": 3.7,
     "text_chunk": "The CD4/CD8 ratio reflects the balance between helper and cytotoxic T lymphocytes. Inverted ratio (<1.0) occurs in HIV, chronic viral infections, immunosenescence, and some autoimmune conditions. A very low ratio in aging populations is associated with increased mortality (immune risk phenotype). High ratios (>3.5) may indicate T-cell lymphoma or certain autoimmune diseases. The ratio is more informative than individual counts for assessing immune homeostasis. Optimal 1.2-3.0.",
     "clinical_significance": "Reflects immune balance; inverted ratio (<1.0) in HIV, infections, immunosenescence; associated with mortality in elderly.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "immune_nk_cells", "name": "NK Cells", "unit": "cells/uL", "category": "Immune",
     "ref_range_min": 60.0, "ref_range_max": 600.0,
     "text_chunk": "Natural killer (NK) cells (CD16+CD56+) provide innate immune surveillance against viral infections and malignant cells without prior antigen sensitization. Low NK cell counts or function increase susceptibility to viral infections and certain cancers. Elevated NK cells occur in acute stress, chronic infections, and some NK-cell lymphoproliferative disorders. NK cell activity assays (cytotoxicity testing) provide functional assessment beyond enumeration. Measured by flow cytometry. Optimal 100-500 cells/uL.",
     "clinical_significance": "Innate immune surveillance against viruses and cancer; low counts increase infection/cancer susceptibility.",
     "epigenetic_clock": None, "genetic_modifiers": "KIR"},

    # === Cancer Screening ===
    {"id": "cancer_free_psa", "name": "Free PSA", "unit": "ng/mL", "category": "Cancer Screening",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Free PSA measures the unbound fraction of prostate-specific antigen in serum. The ratio of free to total PSA (% Free PSA) helps distinguish benign prostatic hyperplasia (BPH) from prostate cancer in men with total PSA 4-10 ng/mL (the diagnostic gray zone). Free PSA is lower in prostate cancer because cancer-associated PSA binds more to protease inhibitors. A % Free PSA >25% suggests BPH, while <10% increases prostate cancer probability.",
     "clinical_significance": "Helps distinguish BPH from prostate cancer in PSA gray zone (4-10); lower free fraction suggests cancer.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "cancer_pct_free_psa", "name": "% Free PSA", "unit": "%", "category": "Cancer Screening",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Percent free PSA is calculated as (Free PSA / Total PSA × 100). Used to risk-stratify men with total PSA 4-10 ng/mL. Values above 25% suggest benign etiology with biopsy often deferred. Values below 10% significantly increase prostate cancer probability and typically warrant biopsy. The cutoff used varies by institution (commonly 25%). Reduces unnecessary biopsies by 20-30% while maintaining cancer detection sensitivity.",
     "clinical_significance": ">25% suggests benign disease (defer biopsy); <10% suggests cancer (proceed to biopsy); reduces unnecessary biopsies by 20-30%.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "cancer_galleri_mced", "name": "Galleri MCED Result", "unit": "", "category": "Cancer Screening",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "The Galleri multi-cancer early detection (MCED) test by GRAIL uses targeted methylation-based cell-free DNA (cfDNA) sequencing to screen for over 50 cancer types from a single blood draw. It detects cancer signals from aberrant DNA methylation patterns in circulating tumor DNA, with a cancer signal origin (CSO) prediction localizing the tissue of origin. Overall sensitivity is ~51.5% across stages I-III with 99.5% specificity (0.5% false positive rate). Intended as a complement to, not replacement for, standard cancer screening.",
     "clinical_significance": "Multi-cancer blood test screening 50+ cancer types via cfDNA methylation; 99.5% specificity; complement to standard screening.",
     "epigenetic_clock": None, "genetic_modifiers": ""},

    # === Protein Electrophoresis ===
    {"id": "protein_spep", "name": "SPEP", "unit": "", "category": "Protein Electrophoresis",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Serum protein electrophoresis (SPEP) separates serum proteins into albumin, alpha-1, alpha-2, beta, and gamma globulin fractions by capillary zone electrophoresis. SPEP detects monoclonal proteins (M-spikes) indicating plasma cell dyscrasias (multiple myeloma, MGUS, Waldenstrom macroglobulinemia). Normal polyclonal pattern shows a broad gamma region. A discrete band (M-spike) requires immunofixation electrophoresis (IFE) for characterization. SPEP also detects chronic inflammation (polyclonal gammopathy) and nephrotic syndrome (low albumin, elevated alpha-2).",
     "clinical_significance": "Screens for monoclonal gammopathies (myeloma, MGUS); detects M-spikes requiring IFE characterization; identifies chronic inflammation patterns.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "protein_alpha1", "name": "Alpha-1 Globulin", "unit": "g/dL", "category": "Protein Electrophoresis",
     "ref_range_min": 0.19, "ref_range_max": 0.46,
     "text_chunk": "Alpha-1 globulin fraction on SPEP primarily contains alpha-1 antitrypsin (AAT) and alpha-1 acid glycoprotein (orosomucoid). Low alpha-1 fraction suggests alpha-1 antitrypsin deficiency (AATD, SERPINA1 gene mutations), which causes early-onset emphysema and liver disease. Elevated alpha-1 occurs as an acute phase response. AATD affects 1 in 2,500-5,000 individuals. Optimal 0.20-0.40 g/dL.",
     "clinical_significance": "Low suggests alpha-1 antitrypsin deficiency (emphysema/liver disease); elevated in acute phase response.",
     "epigenetic_clock": None, "genetic_modifiers": "SERPINA1"},
    {"id": "protein_alpha2", "name": "Alpha-2 Globulin", "unit": "g/dL", "category": "Protein Electrophoresis",
     "ref_range_min": 0.48, "ref_range_max": 1.05,
     "text_chunk": "Alpha-2 globulin fraction contains haptoglobin, alpha-2 macroglobulin, and ceruloplasmin. Elevated alpha-2 occurs in nephrotic syndrome (alpha-2 macroglobulin increases as smaller proteins are lost in urine), acute inflammation, and adrenal insufficiency. Low alpha-2 may indicate hemolysis (haptoglobin consumption) or Wilson disease (low ceruloplasmin). Optimal 0.50-0.90 g/dL.",
     "clinical_significance": "Elevated in nephrotic syndrome and acute inflammation; low in hemolysis (haptoglobin consumption) and Wilson disease.",
     "epigenetic_clock": None, "genetic_modifiers": "HP,CP"},
    {"id": "protein_beta", "name": "Beta Globulin", "unit": "g/dL", "category": "Protein Electrophoresis",
     "ref_range_min": 0.60, "ref_range_max": 1.11,
     "text_chunk": "Beta globulin fraction contains transferrin, complement C3, beta-lipoprotein, and beta-2 microglobulin. Elevated beta fraction occurs in iron deficiency anemia (increased transferrin), monoclonal IgA or IgM (beta-migrating M-spikes), and hypercholesterolemia. Beta-gamma bridging pattern on SPEP is characteristic of cirrhosis. Optimal 0.65-1.00 g/dL.",
     "clinical_significance": "Elevated in iron deficiency (transferrin), beta-migrating M-spikes, hyperlipidemia; beta-gamma bridging suggests cirrhosis.",
     "epigenetic_clock": None, "genetic_modifiers": "TF"},
    {"id": "protein_gamma", "name": "Gamma Globulin", "unit": "g/dL", "category": "Protein Electrophoresis",
     "ref_range_min": 0.64, "ref_range_max": 1.56,
     "text_chunk": "Gamma globulin fraction contains immunoglobulins (IgG, IgA, IgM, IgD, IgE). Polyclonal increase (broad gamma elevation) indicates chronic infection, autoimmune disease, or chronic inflammation. Monoclonal spike within gamma region indicates plasma cell neoplasm (myeloma, MGUS). Decreased gamma (hypogammaglobulinemia) indicates primary or secondary immunodeficiency. Absent gamma fraction is seen in X-linked agammaglobulinemia. Optimal 0.70-1.40 g/dL.",
     "clinical_significance": "Polyclonal elevation in chronic infection/autoimmune disease; monoclonal spike in myeloma/MGUS; decreased in immunodeficiency.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "protein_mspike", "name": "M-Spike", "unit": "", "category": "Protein Electrophoresis",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "M-spike (monoclonal protein) on SPEP is a discrete band representing a single immunoglobulin produced by a clonal plasma cell population. M-spike detection requires immunofixation electrophoresis (IFE) for isotype identification (IgG kappa, IgA lambda, etc.). M-spike <1.5 g/dL with no end-organ damage is classified as MGUS (monoclonal gammopathy of undetermined significance), which has ~1% annual progression rate to myeloma. M-spike >3 g/dL raises concern for multiple myeloma.",
     "clinical_significance": "Detected monoclonal protein requires IFE characterization; <1.5 g/dL likely MGUS (1%/year myeloma progression); >3 g/dL suggests myeloma.",
     "epigenetic_clock": None, "genetic_modifiers": ""},

    # === Urinalysis ===
    {"id": "ua_specific_gravity", "name": "Urine Specific Gravity", "unit": "", "category": "Urinalysis",
     "ref_range_min": 1.005, "ref_range_max": 1.030,
     "text_chunk": "Urine specific gravity measures the concentration of dissolved solutes reflecting the kidney's ability to concentrate urine. Low values (<1.005) indicate dilute urine from excessive fluid intake, diabetes insipidus, or renal tubular damage. High values (>1.030) indicate concentrated urine from dehydration, SIADH, or heavy proteinuria/glycosuria. Fixed specific gravity at 1.010 (isosthenuria) indicates loss of concentrating ability, seen in chronic kidney disease. Measured by refractometry. Optimal 1.010-1.025.",
     "clinical_significance": "Reflects renal concentrating ability; fixed 1.010 indicates CKD; low in diabetes insipidus; high in dehydration.",
     "epigenetic_clock": None, "genetic_modifiers": "AQP2"},
    {"id": "ua_ph", "name": "Urine pH", "unit": "", "category": "Urinalysis",
     "ref_range_min": 4.5, "ref_range_max": 8.0,
     "text_chunk": "Urine pH reflects acid-base balance and dietary composition. Acidic urine (pH <5.5) is normal on meat-heavy diets and occurs in metabolic acidosis, diabetic ketoacidosis, and respiratory acidosis. Alkaline urine (pH >7.0) occurs with vegetarian diets, urinary tract infections (urease-producing organisms), renal tubular acidosis type I and II, and systemic alkalosis. Urine pH affects stone formation: uric acid stones form in acidic urine, struvite and calcium phosphate stones in alkaline urine. Optimal 5.5-7.0.",
     "clinical_significance": "Reflects acid-base status and diet; affects kidney stone type; persistently alkaline may indicate UTI or renal tubular acidosis.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "ua_wbc", "name": "Urine WBC", "unit": "/HPF", "category": "Urinalysis",
     "ref_range_min": None, "ref_range_max": 5.0,
     "text_chunk": "Urine white blood cells (pyuria) above 5 per high-power field indicate urinary tract inflammation, most commonly from infection (UTI). Sterile pyuria (WBC present without bacteria) occurs in partially treated UTI, renal tuberculosis, interstitial nephritis, nephrolithiasis, or genitourinary malignancy. Pyuria combined with positive nitrite and leukocyte esterase strongly suggests bacterial UTI. Measured by microscopy or automated urinalysis.",
     "clinical_significance": ">5/HPF indicates urinary tract inflammation; sterile pyuria requires evaluation for TB, interstitial nephritis, or malignancy.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "ua_rbc", "name": "Urine RBC", "unit": "/HPF", "category": "Urinalysis",
     "ref_range_min": None, "ref_range_max": 3.0,
     "text_chunk": "Urine red blood cells (hematuria) above 3 per high-power field indicate bleeding from anywhere in the urinary tract. Glomerular hematuria (dysmorphic RBCs, RBC casts) suggests glomerulonephritis. Non-glomerular hematuria (isomorphic RBCs) suggests stones, infection, malignancy, or prostatic disease. Microscopic hematuria in adults over 40 requires cystoscopy and imaging to exclude bladder cancer. Exercise-induced hematuria is transient and benign.",
     "clinical_significance": ">3/HPF requires evaluation; dysmorphic RBCs suggest glomerulonephritis; adults >40 need cystoscopy to exclude malignancy.",
     "epigenetic_clock": None, "genetic_modifiers": "COL4A3,COL4A4,COL4A5"},

    # === Heavy Metals ===
    {"id": "toxicology_mercury", "name": "Mercury Blood", "unit": "ug/L", "category": "Toxicology",
     "ref_range_min": None, "ref_range_max": 5.0,
     "text_chunk": "Blood mercury reflects recent methylmercury exposure primarily from seafood consumption. Methylmercury is a potent neurotoxin that bioaccumulates in the food chain. Levels above 5 ug/L warrant dietary counseling to reduce high-mercury fish (swordfish, shark, king mackerel, tilefish). Levels above 10 ug/L may cause neurological symptoms (paresthesias, tremor, cognitive impairment). Measured by ICP-MS or cold vapor atomic absorption. Optimal below 3 ug/L.",
     "clinical_significance": "Reflects methylmercury from seafood; >5 ug/L requires dietary modification; >10 ug/L may cause neurological symptoms.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "toxicology_lead", "name": "Lead Blood", "unit": "ug/dL", "category": "Toxicology",
     "ref_range_min": None, "ref_range_max": 3.5,
     "text_chunk": "Blood lead level reflects recent lead exposure. No safe level of lead has been identified. CDC reference value for adults is <3.5 ug/dL (updated 2021). Elevated lead causes neurotoxicity, nephrotoxicity, anemia (basophilic stippling), and hypertension. Occupational exposure (construction, smelting, battery manufacturing) is the primary adult source. Children are more susceptible due to developing nervous system. Measured by ICP-MS or graphite furnace AAS. Optimal below 2 ug/dL.",
     "clinical_significance": "No safe level exists; >3.5 ug/dL requires source identification; causes neurotoxicity, nephrotoxicity, anemia; children especially susceptible.",
     "epigenetic_clock": None, "genetic_modifiers": "ALAD"},
    {"id": "toxicology_arsenic", "name": "Arsenic Urine", "unit": "ug/L", "category": "Toxicology",
     "ref_range_min": None, "ref_range_max": 50.0,
     "text_chunk": "Urine arsenic (total) measures recent arsenic exposure. Inorganic arsenic (from contaminated water, rice, occupational exposure) is a class 1 carcinogen causing skin, lung, and bladder cancer. Organic arsenic from seafood (arsenobetaine) is non-toxic and can elevate total arsenic; speciation testing distinguishes organic from inorganic forms. Levels above 50 ug/L warrant speciation and source investigation. Measured by ICP-MS. Optimal below 30 ug/L.",
     "clinical_significance": "Inorganic arsenic is a class 1 carcinogen; >50 ug/L requires speciation testing; seafood can cause benign organic arsenic elevation.",
     "epigenetic_clock": None, "genetic_modifiers": "AS3MT"},
    {"id": "toxicology_cadmium", "name": "Cadmium Blood", "unit": "ug/L", "category": "Toxicology",
     "ref_range_min": None, "ref_range_max": 2.0,
     "text_chunk": "Blood cadmium reflects recent cadmium exposure, primarily from cigarette smoke and industrial sources. Cadmium accumulates in the kidney with a biological half-life of 10-30 years, causing proximal tubular damage (Fanconi syndrome) and osteomalacia. Cadmium is a class 1 carcinogen (lung cancer). Blood cadmium >2 ug/L in non-smokers warrants occupational/environmental investigation. Measured by ICP-MS or graphite furnace AAS. Optimal below 1 ug/L.",
     "clinical_significance": "Primarily from smoking/industry; accumulates in kidneys (30-year half-life); causes tubular damage, osteomalacia; class 1 carcinogen.",
     "epigenetic_clock": None, "genetic_modifiers": "MT1A,MT2A"},

    # === Extended Vitamins ===
    {"id": "vitamins_folate_rbc", "name": "Folate RBC", "unit": "ng/mL", "category": "Vitamins",
     "ref_range_min": 280.0, "ref_range_max": 791.0,
     "text_chunk": "Red blood cell (RBC) folate reflects tissue folate stores over the preceding 120 days (RBC lifespan), providing a more stable measure than serum folate which fluctuates with recent dietary intake. Low RBC folate (<280 ng/mL) confirms folate deficiency even when serum folate is normal. Critical for MTHFR variant carriers who may have normal serum folate but impaired cellular folate metabolism. Measured by chemiluminescent immunoassay from whole blood. Optimal 400-700 ng/mL.",
     "clinical_significance": "More stable than serum folate (reflects 120-day stores); critical for confirming deficiency in MTHFR carriers with normal serum folate.",
     "epigenetic_clock": None, "genetic_modifiers": "MTHFR,DHFR,SLC19A1"},
    {"id": "vitamins_c", "name": "Vitamin C", "unit": "mg/dL", "category": "Vitamins",
     "ref_range_min": 0.4, "ref_range_max": 2.0,
     "text_chunk": "Vitamin C (ascorbic acid) is an essential water-soluble antioxidant required for collagen synthesis, immune function, and iron absorption. Deficiency (<0.4 mg/dL) causes scurvy (bleeding gums, poor wound healing, petechiae). Suboptimal levels are common in smokers, alcoholics, and elderly with restricted diets. Measured by HPLC with electrochemical detection from EDTA plasma. Specimen must be processed quickly as vitamin C degrades rapidly. Optimal 0.8-1.8 mg/dL.",
     "clinical_significance": "Essential antioxidant; deficiency causes scurvy; common in smokers and elderly; specimen degrades rapidly requiring prompt processing.",
     "epigenetic_clock": None, "genetic_modifiers": "SLC23A1,SLC23A2"},
    {"id": "vitamins_b1", "name": "Vitamin B1 Thiamine", "unit": "nmol/L", "category": "Vitamins",
     "ref_range_min": 70.0, "ref_range_max": 180.0,
     "text_chunk": "Vitamin B1 (thiamine) is essential for carbohydrate metabolism and neuronal function. Deficiency causes beriberi (wet: cardiac failure; dry: peripheral neuropathy) and Wernicke-Korsakoff syndrome in alcoholics. Thiamine deficiency is common in chronic alcoholism, bariatric surgery patients, prolonged ICU stays, and refeeding syndrome. Measured by LC-MS/MS from whole blood. Whole blood thiamine diphosphate (TDP) is the preferred functional marker. Optimal 80-150 nmol/L.",
     "clinical_significance": "Deficiency causes beriberi and Wernicke-Korsakoff syndrome; common in alcoholism, bariatric surgery, refeeding; whole blood TDP is preferred marker.",
     "epigenetic_clock": None, "genetic_modifiers": "SLC19A2"},
    {"id": "vitamins_b2", "name": "Vitamin B2 Riboflavin", "unit": "nmol/L", "category": "Vitamins",
     "ref_range_min": 6.2, "ref_range_max": 39.0,
     "text_chunk": "Vitamin B2 (riboflavin) is a precursor to FAD and FMN coenzymes essential for energy metabolism, cellular function, and MTHFR enzyme activity. Riboflavin deficiency (ariboflavinosis) causes angular stomatitis, glossitis, dermatitis, and normocytic anemia. Riboflavin is required for MTHFR function; supplementation can lower homocysteine in MTHFR 677TT homozygotes. Measured by HPLC with fluorometric detection from plasma. Optimal 7-30 nmol/L.",
     "clinical_significance": "Essential for MTHFR enzyme function; supplementation lowers homocysteine in MTHFR 677TT carriers; deficiency causes stomatitis and anemia.",
     "epigenetic_clock": None, "genetic_modifiers": "MTHFR"},
    {"id": "vitamins_k1", "name": "Vitamin K1", "unit": "ng/mL", "category": "Vitamins",
     "ref_range_min": 0.1, "ref_range_max": 2.2,
     "text_chunk": "Vitamin K1 (phylloquinone) is essential for synthesis of coagulation factors (II, VII, IX, X, protein C, protein S) and osteocalcin (bone metabolism). Deficiency causes coagulopathy (elevated PT/INR) and impaired bone mineralization. Vitamin K antagonists (warfarin) work by inhibiting vitamin K recycling. Supplementation can reverse warfarin over-anticoagulation. Measured by LC-MS/MS from serum. K2 (menaquinone) has distinct bone and cardiovascular benefits. Optimal 0.5-2.0 ng/mL.",
     "clinical_significance": "Essential for coagulation factor synthesis and bone mineralization; deficiency causes coagulopathy; K1 reverses warfarin over-anticoagulation.",
     "epigenetic_clock": None, "genetic_modifiers": "VKORC1,GGCX"},
    {"id": "vitamins_mma", "name": "Methylmalonic Acid", "unit": "nmol/L", "category": "Vitamins",
     "ref_range_min": None, "ref_range_max": 378.0,
     "text_chunk": "Methylmalonic acid (MMA) is a functional biomarker of vitamin B12 (cobalamin) status at the tissue level. Elevated MMA indicates functional B12 deficiency even when serum B12 is within the normal range (functional B12 deficiency). MMA is more specific for B12 deficiency than homocysteine (which also rises with folate deficiency). Levels above 378 nmol/L suggest B12 deficiency requiring supplementation. Renal impairment can also elevate MMA. Measured by LC-MS/MS from serum. Optimal below 250 nmol/L.",
     "clinical_significance": "Most specific functional marker of B12 deficiency; elevated when serum B12 is falsely normal; renal impairment can also elevate.",
     "epigenetic_clock": None, "genetic_modifiers": "TCN2,FUT2"},
    {"id": "vitamins_coq10", "name": "CoQ10", "unit": "mg/L", "category": "Vitamins",
     "ref_range_min": 0.37, "ref_range_max": 2.2,
     "text_chunk": "Coenzyme Q10 (ubiquinone) is a lipid-soluble antioxidant essential for mitochondrial electron transport chain function. Statin therapy reduces CoQ10 synthesis by inhibiting the shared mevalonate pathway (HMG-CoA reductase produces both cholesterol and CoQ10). Low CoQ10 may contribute to statin-associated myopathy. Supplementation (100-200 mg/day) is commonly recommended with statin use. Measured by HPLC from serum. Optimal 0.8-2.0 mg/L.",
     "clinical_significance": "Depleted by statin therapy (shared synthesis pathway); low levels may contribute to statin myopathy; supplementation recommended with statins.",
     "epigenetic_clock": None, "genetic_modifiers": "COQ2,PDSS2"},
    {"id": "vitamins_omega6_3_ratio", "name": "Omega-6/Omega-3 Ratio", "unit": "ratio", "category": "Vitamins",
     "ref_range_min": None, "ref_range_max": 4.0,
     "text_chunk": "The omega-6 to omega-3 fatty acid ratio reflects the balance between pro-inflammatory (omega-6, arachidonic acid) and anti-inflammatory (omega-3, EPA/DHA) fatty acids in red blood cell membranes. Western diets typically have ratios of 15-20:1, far exceeding the optimal ratio of <4:1. High ratios promote systemic inflammation and are associated with cardiovascular disease, autoimmune disorders, and cancer. Measured by gas chromatography from RBC membranes. Optimal below 3:1.",
     "clinical_significance": "Reflects pro-inflammatory vs anti-inflammatory fatty acid balance; Western diets typically 15-20:1; optimal <4:1; modifiable through diet.",
     "epigenetic_clock": None, "genetic_modifiers": "FADS1,FADS2"},
    {"id": "vitamins_aa_epa_ratio", "name": "AA/EPA Ratio", "unit": "ratio", "category": "Vitamins",
     "ref_range_min": None, "ref_range_max": 5.0,
     "text_chunk": "The arachidonic acid (AA) to eicosapentaenoic acid (EPA) ratio is a specific marker of inflammatory eicosanoid balance. AA is the precursor to pro-inflammatory prostaglandins (PGE2), thromboxanes (TXA2), and leukotrienes (LTB4), while EPA produces anti-inflammatory resolvins and protectins. Ratios above 5 indicate pro-inflammatory dominance. Measured by gas chromatography from RBC membranes. Optimal below 3. Ratio is highly responsive to EPA/DHA supplementation (typically improves within 8-12 weeks).",
     "clinical_significance": "Specific marker of inflammatory eicosanoid balance; >5 indicates pro-inflammatory dominance; rapidly responsive to omega-3 supplementation.",
     "epigenetic_clock": None, "genetic_modifiers": "FADS1,FADS2"},

    # === Minerals Extended ===
    {"id": "minerals_chromium", "name": "Chromium", "unit": "ug/L", "category": "Vitamins",
     "ref_range_min": 0.1, "ref_range_max": 2.1,
     "text_chunk": "Chromium is a trace mineral that may enhance insulin signaling through chromodulin activation. Deficiency is rare but may impair glucose tolerance. Supplementation studies show mixed results for glycemic control. Elevated chromium indicates occupational exposure (welding, chrome plating) and can cause lung cancer, kidney damage, and allergic dermatitis. Measured by ICP-MS from serum. Clinical utility of routine chromium testing is limited.",
     "clinical_significance": "May enhance insulin signaling; deficiency rare; elevated indicates occupational exposure; clinical utility of testing is limited.",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "minerals_manganese", "name": "Manganese", "unit": "ug/L", "category": "Vitamins",
     "ref_range_min": 0.4, "ref_range_max": 1.1,
     "text_chunk": "Manganese is a cofactor for mitochondrial superoxide dismutase (MnSOD), arginase, and pyruvate carboxylase. Deficiency is rare in humans. Toxicity (manganism) from occupational inhalation causes parkinsonism-like neurotoxicity. Elevated blood manganese in non-occupational settings may indicate liver disease (impaired biliary excretion) or parenteral nutrition without manganese monitoring. Measured by ICP-MS from whole blood. Optimal 0.5-1.0 ug/L.",
     "clinical_significance": "Essential cofactor for MnSOD; toxicity causes parkinsonism; elevated in liver disease (impaired biliary excretion).",
     "epigenetic_clock": None, "genetic_modifiers": "SLC30A10"},
    {"id": "minerals_cu_zn_ratio", "name": "Copper/Zinc Ratio", "unit": "ratio", "category": "Vitamins",
     "ref_range_min": 0.7, "ref_range_max": 1.0,
     "text_chunk": "The copper/zinc ratio reflects the balance between these antagonistic trace minerals. Elevated ratio (>1.0) indicates relative copper excess or zinc deficiency, associated with oxidative stress, inflammation, impaired immune function, and accelerated aging. High Cu/Zn ratios are found in chronic inflammation, infection, cardiovascular disease, and neurodegeneration. Zinc supplementation may help normalize the ratio. Optimal 0.7-1.0.",
     "clinical_significance": "Elevated ratio indicates oxidative stress and inflammation; associated with CV disease and neurodegeneration; normalizable with zinc supplementation.",
     "epigenetic_clock": None, "genetic_modifiers": "SLC39A4,ATP7A,ATP7B"},

    # === Female Hormones ===
    {"id": "hormones_free_testosterone", "name": "Free Testosterone", "unit": "pg/mL", "category": "Hormones",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Free testosterone is the biologically active (unbound) fraction of total testosterone, comprising only 1-3% of total testosterone. The remainder is bound to SHBG (60-70%) and albumin (30-40%). Free testosterone is the most clinically relevant measure when SHBG is altered (obesity lowers SHBG falsely elevating free T; OCP/aging raises SHBG falsely lowering free T). Male reference: 6.8-21.5 pg/mL (optimal 10-20). Female reference: 0.3-4.1 pg/mL (optimal 0.5-3.0). Measured by equilibrium dialysis + LC-MS/MS (gold standard).",
     "clinical_significance": "Most clinically relevant testosterone measure when SHBG is altered; sex-specific ranges critical; equilibrium dialysis is gold standard method.",
     "epigenetic_clock": None, "genetic_modifiers": "AR,SHBG"},
    {"id": "hormones_shbg", "name": "SHBG", "unit": "nmol/L", "category": "Hormones",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Sex hormone binding globulin (SHBG) is a glycoprotein that binds and transports sex steroids (testosterone, estradiol, DHT). SHBG determines the bioavailability of sex hormones. Elevated SHBG (from OCP use, hyperthyroidism, liver disease, aging) reduces free testosterone. Low SHBG (from obesity, insulin resistance, hypothyroidism, androgens) increases free testosterone. Male reference: 16.5-55.9 nmol/L. Female reference: 24.6-122 nmol/L. Measured by immunoassay.",
     "clinical_significance": "Determines sex hormone bioavailability; elevated by OCP/aging/liver disease; reduced by obesity/insulin resistance; sex-specific ranges.",
     "epigenetic_clock": None, "genetic_modifiers": "SHBG"},
    {"id": "hormones_fsh", "name": "FSH", "unit": "mIU/mL", "category": "Hormones",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Follicle-stimulating hormone (FSH) is a pituitary gonadotropin that stimulates folliculogenesis in women and spermatogenesis in men. Elevated FSH indicates primary gonadal failure (menopause, premature ovarian insufficiency, Klinefelter syndrome). Low FSH suggests hypothalamic-pituitary dysfunction. In women, day-3 FSH >10-12 mIU/mL indicates diminished ovarian reserve. FSH rises during perimenopause before menstrual irregularity. Male ref: 1.5-12.4 mIU/mL. Female follicular ref: 3.5-12.5 mIU/mL. Postmenopausal: >25 mIU/mL.",
     "clinical_significance": "Elevated in primary gonadal failure/menopause; day-3 FSH assesses ovarian reserve; rises in perimenopause before clinical symptoms.",
     "epigenetic_clock": None, "genetic_modifiers": "FSHB,FSHR"},
    {"id": "hormones_lh", "name": "LH", "unit": "mIU/mL", "category": "Hormones",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Luteinizing hormone (LH) is a pituitary gonadotropin that triggers ovulation and corpus luteum formation in women and stimulates Leydig cell testosterone production in men. LH surge at mid-cycle triggers ovulation. Elevated baseline LH with elevated LH/FSH ratio (>2:1) suggests polycystic ovary syndrome (PCOS). Elevated LH in men indicates primary hypogonadism (testicular failure). Male ref: 1.7-8.6 mIU/mL. Female follicular: 2.4-12.6 mIU/mL. Mid-cycle surge: 14-96 mIU/mL.",
     "clinical_significance": "Triggers ovulation; elevated LH/FSH ratio >2:1 suggests PCOS; elevated in primary hypogonadism; sex and cycle-phase dependent.",
     "epigenetic_clock": None, "genetic_modifiers": "LHB,LHCGR"},
    {"id": "hormones_prolactin", "name": "Prolactin", "unit": "ng/mL", "category": "Hormones",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Prolactin is a pituitary hormone primarily involved in lactation. Elevated prolactin (hyperprolactinemia) causes galactorrhea, amenorrhea, and infertility in women; hypogonadism and erectile dysfunction in men. Causes include prolactinoma (pituitary adenoma), medications (antipsychotics, metoclopramide), hypothyroidism, and renal failure. Macroprolactin (biologically inactive IgG-bound prolactin) can cause falsely elevated results; PEG precipitation identifies macroprolactinemia. Male ref: 4-15.2 ng/mL. Female ref: 4.8-23.3 ng/mL.",
     "clinical_significance": "Elevated causes galactorrhea/amenorrhea/infertility; common causes include prolactinoma and medications; macroprolactin causes false elevations.",
     "epigenetic_clock": None, "genetic_modifiers": "PRL"},
    {"id": "hormones_amh", "name": "AMH", "unit": "ng/mL", "category": "Hormones",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Anti-Mullerian hormone (AMH) is produced by granulosa cells of preantral and small antral ovarian follicles. AMH is the best biomarker of ovarian reserve, remaining relatively stable throughout the menstrual cycle. Low AMH (<1.0 ng/mL) indicates diminished ovarian reserve with reduced response to ovarian stimulation in IVF. Very low AMH (<0.1 ng/mL) suggests approaching menopause. In males, AMH assesses Sertoli cell function. Female ref: 0.9-9.5 ng/mL. Male ref: 0.7-19.0 ng/mL. Measured by electrochemiluminescent immunoassay.",
     "clinical_significance": "Best ovarian reserve biomarker; cycle-independent; low AMH predicts poor IVF response; very low suggests approaching menopause.",
     "epigenetic_clock": None, "genetic_modifiers": "AMH,AMHR2"},
    {"id": "hormones_dht", "name": "DHT", "unit": "ng/dL", "category": "Hormones",
     "ref_range_min": 14.0, "ref_range_max": 77.0,
     "text_chunk": "Dihydrotestosterone (DHT) is the most potent androgen, formed from testosterone by 5-alpha reductase (types 1 and 2). DHT mediates prostate growth, male pattern hair loss, acne, and hirsutism. In males, elevated DHT is associated with BPH and androgenetic alopecia. 5-alpha reductase inhibitors (finasteride, dutasteride) reduce DHT by 60-90% to treat BPH and hair loss. In females, elevated DHT contributes to PCOS-related hirsutism. Male ref: 14-77 ng/dL. Measured by LC-MS/MS.",
     "clinical_significance": "Most potent androgen; elevated in BPH and androgenetic alopecia; target of 5-alpha reductase inhibitors; elevated in PCOS-related hirsutism.",
     "epigenetic_clock": None, "genetic_modifiers": "SRD5A2,AR"},

    # === Genetic Markers ===
    {"id": "genetic_apoe_genotype", "name": "ApoE Genotype", "unit": "genotype", "category": "Genetic",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Apolipoprotein E (APOE) genotype determined by rs429358 and rs7412 SNPs defines six genotypes (E2/E2, E2/E3, E2/E4, E3/E3, E3/E4, E4/E4). The E4 allele is the strongest common genetic risk factor for late-onset Alzheimer disease (3-4x risk for E3/E4, 12-15x for E4/E4) and also increases LDL cholesterol and cardiovascular risk. E2 allele is protective against Alzheimer but increases type III hyperlipoproteinemia risk. Determined by PCR + TaqMan SNP genotyping from DNA. Results are lifelong and unchanging.",
     "clinical_significance": "Strongest common genetic AD risk factor; E4 also increases LDL/CVD risk; E2 protective for AD but raises type III hyperlipidemia risk; lifelong result.",
     "epigenetic_clock": None, "genetic_modifiers": "APOE"},
    {"id": "genetic_apoe_protein", "name": "ApoE Protein Level", "unit": "mg/dL", "category": "Genetic",
     "ref_range_min": 2.7, "ref_range_max": 6.7,
     "text_chunk": "Apolipoprotein E protein level in serum reflects hepatic ApoE production. ApoE is essential for lipoprotein metabolism, mediating clearance of triglyceride-rich remnant particles via LDL receptor family. ApoE levels vary by genotype: E4 carriers typically have lower ApoE levels with less efficient remnant clearance. Low ApoE protein may indicate E4 homozygosity or liver dysfunction. Measured by immunoturbidimetry. Optimal 3-6 mg/dL. Complements genotype testing by assessing functional protein expression.",
     "clinical_significance": "Reflects hepatic ApoE production; varies by genotype (E4 carriers have lower levels); complements genotype testing for functional assessment.",
     "epigenetic_clock": None, "genetic_modifiers": "APOE"},
    {"id": "genetic_mthfr_c677t", "name": "MTHFR C677T", "unit": "genotype", "category": "Genetic",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "MTHFR C677T (rs1801133) is the most clinically significant MTHFR variant. CT heterozygotes have ~65% enzyme activity; TT homozygotes have ~30% activity with increased homocysteine levels. The T allele frequency is 25-35% in European populations. TT homozygotes require methylfolate supplementation (not folic acid, which requires MTHFR for activation). MTHFR status affects neural tube defect risk, cardiovascular risk, and response to methotrexate therapy. Determined by PCR + TaqMan SNP genotyping.",
     "clinical_significance": "CT: ~65% activity; TT: ~30% activity with elevated homocysteine; TT requires methylfolate (not folic acid); affects NTD risk and methotrexate response.",
     "epigenetic_clock": None, "genetic_modifiers": "MTHFR"},
    {"id": "genetic_mthfr_a1298c", "name": "MTHFR A1298C", "unit": "genotype", "category": "Genetic",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "MTHFR A1298C (rs1801131) is a second common MTHFR variant with milder effect than C677T. CC homozygotes have mildly reduced enzyme activity. A1298C alone rarely causes significant hyperhomocysteinemia, but compound heterozygosity (C677T CT + A1298C AC) can cause clinically relevant enzyme reduction similar to C677T TT. Determined by PCR + TaqMan SNP genotyping. Compound heterozygotes may benefit from methylfolate supplementation.",
     "clinical_significance": "Milder effect than C677T alone; compound heterozygosity (677CT + 1298AC) clinically significant; may benefit from methylfolate.",
     "epigenetic_clock": None, "genetic_modifiers": "MTHFR"},

    # === Thyroid Extended ===
    {"id": "thyroid_t3_uptake", "name": "T3 Uptake", "unit": "%", "category": "Thyroid",
     "ref_range_min": 24.0, "ref_range_max": 39.0,
     "text_chunk": "T3 uptake (T3RU) is an indirect measure of thyroxine-binding globulin (TBG) saturation, not a direct measure of T3. Low T3 uptake indicates high TBG (pregnancy, OCP, hepatitis) meaning more binding sites are available. High T3 uptake indicates low TBG (nephrotic syndrome, androgens) or TBG saturation from hyperthyroidism. T3 uptake is used to calculate the Free Thyroxine Index (FTI = T4 × T3 Uptake). Optimal 28-35%.",
     "clinical_significance": "Indirect measure of TBG saturation, not T3 levels; used to calculate FTI; low in high-TBG states (pregnancy, OCP).",
     "epigenetic_clock": None, "genetic_modifiers": "SERPINA7"},
    {"id": "thyroid_fti", "name": "Free Thyroxine Index", "unit": "index", "category": "Thyroid",
     "ref_range_min": 1.2, "ref_range_max": 4.9,
     "text_chunk": "Free Thyroxine Index (FTI) is calculated as Total T4 × T3 Uptake to estimate free T4 when direct free T4 measurement may be unreliable (pregnancy, severe illness, TBG abnormalities). FTI corrects for TBG variation that affects total T4. Largely superseded by direct free T4 immunoassays in routine practice but still useful when free T4 results are discordant with clinical presentation. Optimal 1.5-4.0.",
     "clinical_significance": "Estimates free T4 corrected for TBG variation; useful when direct free T4 is unreliable (pregnancy, severe illness, TBG abnormalities).",
     "epigenetic_clock": None, "genetic_modifiers": ""},
    {"id": "thyroid_tgab", "name": "Thyroglobulin Antibodies", "unit": "IU/mL", "category": "Thyroid",
     "ref_range_min": None, "ref_range_max": 0.9,
     "text_chunk": "Thyroglobulin antibodies (TgAb) target thyroglobulin, the thyroid hormone precursor stored in follicular colloid. TgAb are found in Hashimoto thyroiditis (50-80%), Graves disease (50-70%), and thyroid cancer follow-up (interfere with thyroglobulin tumor marker measurement). TgAb positivity can indicate early thyroid autoimmunity before clinical hypothyroidism develops. In thyroid cancer surveillance, TgAb >0.9 IU/mL invalidates thyroglobulin measurements. Measured by chemiluminescent immunoassay.",
     "clinical_significance": "Marker of thyroid autoimmunity (Hashimoto's, Graves); interferes with thyroglobulin cancer marker; >0.9 IU/mL requires serial TgAb trending instead.",
     "epigenetic_clock": None, "genetic_modifiers": "HLA-DR3,CTLA4"},
    {"id": "thyroid_thyroglobulin", "name": "Thyroglobulin", "unit": "ng/mL", "category": "Thyroid",
     "ref_range_min": 1.5, "ref_range_max": 38.5,
     "text_chunk": "Thyroglobulin (Tg) is the precursor protein for thyroid hormone synthesis stored in thyroid follicles. Serum Tg is primarily used as a tumor marker after thyroidectomy for differentiated thyroid cancer (DTC): detectable Tg after total thyroidectomy suggests persistent or recurrent disease. In the non-thyroidectomy setting, Tg levels reflect thyroid mass and TSH stimulation. TgAb positivity invalidates Tg measurement. Measured by immunoassay. Normal 1.5-38.5 ng/mL. Post-thyroidectomy target: undetectable.",
     "clinical_significance": "Primary tumor marker for differentiated thyroid cancer after thyroidectomy; detectable post-thyroidectomy suggests recurrence; invalidated by TgAb.",
     "epigenetic_clock": None, "genetic_modifiers": "TG"},
    {"id": "thyroid_tbg", "name": "TBG", "unit": "ug/mL", "category": "Thyroid",
     "ref_range_min": 13.0, "ref_range_max": 39.0,
     "text_chunk": "Thyroxine-binding globulin (TBG) is the primary transport protein for thyroid hormones in serum (binds ~70% of circulating T4 and T3). Elevated TBG (from estrogen/OCP, pregnancy, hepatitis, genetic TBG excess) raises total T4/T3 without affecting free hormone levels or thyroid function. Low TBG (from androgens, nephrotic syndrome, glucocorticoids, genetic TBG deficiency) lowers total T4/T3 without true hypothyroidism. Understanding TBG status prevents misinterpretation of total thyroid hormone levels. Optimal 15-30 ug/mL.",
     "clinical_significance": "Primary thyroid hormone carrier; elevated by estrogen/OCP/pregnancy affecting total T4; key to preventing misdiagnosis of thyroid dysfunction.",
     "epigenetic_clock": None, "genetic_modifiers": "SERPINA7"},
    {"id": "thyroid_t3_rt3_ratio", "name": "T3/rT3 Ratio", "unit": "ratio", "category": "Thyroid",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "The T3 to reverse T3 (rT3) ratio reflects the balance between active thyroid hormone (T3) and its inactive metabolite (rT3). Low T3/rT3 ratio (<6) suggests euthyroid sick syndrome (non-thyroidal illness syndrome), where the body preferentially converts T4 to rT3 instead of active T3 during critical illness, caloric restriction, or chronic stress. This is a protective metabolic adaptation. DIO2 genotype affects T4-to-T3 conversion efficiency. Optimal ratio >6.",
     "clinical_significance": "Low ratio suggests euthyroid sick syndrome or impaired T4-to-T3 conversion; DIO2 genotype modulates conversion efficiency.",
     "epigenetic_clock": None, "genetic_modifiers": "DIO2,DIO1"},

    # === Coagulation ===
    {"id": "coag_ptt", "name": "PTT", "unit": "seconds", "category": "Coagulation",
     "ref_range_min": 25.0, "ref_range_max": 35.0,
     "text_chunk": "Partial thromboplastin time (aPTT) measures the intrinsic and common coagulation pathways (factors XII, XI, IX, VIII, X, V, II, fibrinogen). Prolonged aPTT occurs with heparin therapy, factor deficiencies (hemophilia A/B), lupus anticoagulant, and liver disease. aPTT is used to monitor unfractionated heparin therapy (target 1.5-2.5x control). Unexplained aPTT prolongation with normal PT suggests factor VIII, IX, XI, or XII deficiency or lupus anticoagulant. Optimal 26-33 seconds.",
     "clinical_significance": "Measures intrinsic pathway; monitors heparin therapy; prolonged in hemophilia and lupus anticoagulant; unexplained prolongation needs mixing study.",
     "epigenetic_clock": None, "genetic_modifiers": "F8,F9,F11,F12"},

    # === Blood Type ===
    {"id": "blood_abo", "name": "ABO Blood Type", "unit": "", "category": "Blood Type",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "ABO blood type (A, B, AB, O) is determined by carbohydrate antigens on red blood cell surfaces encoded by the ABO gene. Blood type has implications beyond transfusion medicine: type O is associated with lower von Willebrand factor and factor VIII levels (increased bleeding risk), lower VTE risk, and possibly lower cardiovascular disease risk. Type A is associated with higher VTE and stroke risk. ABO typing is essential before transfusion, organ transplant, and for paternity testing. Determined by agglutination testing.",
     "clinical_significance": "Type O associated with lower VWF/FVIII and bleeding risk; Type A associated with higher VTE/stroke risk; essential for transfusion safety.",
     "epigenetic_clock": None, "genetic_modifiers": "ABO,FUT1"},
    {"id": "blood_rh", "name": "Rh Factor", "unit": "", "category": "Blood Type",
     "ref_range_min": None, "ref_range_max": None,
     "text_chunk": "Rh factor (Rh D antigen) is the most immunogenic non-ABO red cell antigen. Rh-negative individuals exposed to Rh-positive blood (transfusion or pregnancy) develop anti-D antibodies causing hemolytic transfusion reactions or hemolytic disease of the fetus and newborn (HDFN). Rh-negative women carrying Rh-positive fetuses require anti-D immunoglobulin (RhoGAM) at 28 weeks and postpartum. Approximately 15% of Caucasians are Rh-negative. Determined by agglutination with anti-D reagent.",
     "clinical_significance": "Rh-negative women need RhoGAM in pregnancy to prevent HDFN; 15% of Caucasians are Rh-negative; critical for transfusion safety.",
     "epigenetic_clock": None, "genetic_modifiers": "RHD"},
]


def main():
    with open(REF_FILE) as f:
        existing = json.load(f)

    existing_ids = {e['id'] for e in existing}
    added = 0
    skipped = 0

    for bm in NEW_BIOMARKERS:
        if bm['id'] in existing_ids:
            skipped += 1
            continue
        existing.append(bm)
        existing_ids.add(bm['id'])
        added += 1

    # Sort by category then name
    existing.sort(key=lambda x: (x['category'], x['name']))

    with open(REF_FILE, 'w') as f:
        json.dump(existing, f, indent=2)

    categories = sorted(set(e['category'] for e in existing))
    print("Biomarker reference expansion complete:")
    print(f"  Added: {added} new biomarkers")
    print(f"  Skipped: {skipped} (already existed)")
    print(f"  Total: {len(existing)} biomarkers")
    print(f"  Categories ({len(categories)}): {', '.join(categories)}")


if __name__ == '__main__':
    main()
