"""Precision Biomarker Agent -- 12-Section Patient Report Generator.

Takes an AnalysisResult and generates a structured clinical report in
markdown format covering biological age, disease trajectories,
pharmacogenomics, nutritional analysis, and actionable recommendations.

Sections:
 1. Biological Age Assessment
 2. Executive Findings (top 5 critical/high priority)
 3. Biomarker-Gene Correlation Map
 4. Disease Trajectory Analysis (6 diseases)
 5. Pharmacogenomic Profile
 6. Nutritional Analysis
 7. Interconnected Pathways
 8. Prioritized Action Plan
 9. Monitoring Schedule
10. Supplement Protocol Summary
11. Clinical Summary for MD
12. References

Author: Adam Jones
Date: March 2026
"""

from datetime import datetime, timezone
from typing import Dict, List, Optional

from .models import (
    AnalysisResult,
    DiseaseTrajectoryResult,
    GenotypeAdjustmentResult,
    PatientProfile,
    PGxResult,
    RiskLevel,
)

VERSION = "1.0.0"


class ReportGenerator:
    """Generates structured 12-section precision biomarker reports.

    Usage:
        generator = ReportGenerator()
        markdown = generator.generate(analysis_result, patient_profile)
    """

    def generate(self, analysis: AnalysisResult,
                 patient_profile: Optional[PatientProfile] = None) -> str:
        """Generate a complete 12-section patient report in markdown.

        Args:
            analysis: AnalysisResult from PrecisionBiomarkerAgent.analyze_patient().
            patient_profile: Optional override; defaults to analysis.patient_profile.

        Returns:
            Complete markdown report string.
        """
        profile = patient_profile or analysis.patient_profile
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        sections = [
            self._header(profile, timestamp),
            self._section_1_biological_age(analysis),
            self._section_2_executive_findings(analysis),
            self._section_3_biomarker_gene_map(analysis),
            self._section_4_disease_trajectories(analysis),
            self._section_5_pharmacogenomic_profile(analysis),
            self._section_6_nutritional_analysis(analysis, profile),
            self._section_7_interconnected_pathways(analysis),
            self._section_8_action_plan(analysis),
            self._section_9_monitoring_schedule(analysis),
            self._section_10_supplement_protocol(analysis, profile),
            self._section_11_clinical_summary(analysis),
            self._section_12_references(),
            self._section_13_clinical_validation(analysis),
            self._footer(timestamp),
        ]

        return "\n\n".join(sections)

    # -- Header & Footer ---------------------------------------------------

    def _header(self, profile: PatientProfile, timestamp: str) -> str:
        return (
            f"# Precision Biomarker Intelligence Report\n\n"
            f"**Patient ID:** {profile.patient_id}\n"
            f"**Age:** {profile.age} | **Sex:** {profile.sex}\n"
            f"**Generated:** {timestamp}\n"
            f"**Report Version:** {VERSION}\n\n"
            f"---"
        )

    def _footer(self, timestamp: str) -> str:
        from .knowledge import KNOWLEDGE_VERSION

        lines = [
            "---",
            "",
            f"*Knowledge base v{KNOWLEDGE_VERSION['version']} "
            f"(updated {KNOWLEDGE_VERSION['last_updated']}). "
            f"CPIC guidelines: {KNOWLEDGE_VERSION['cpic_version']}. "
            f"ADA Standards: {KNOWLEDGE_VERSION['ada_standards']}.*",
            "",
            f"*Generated by HCLS AI Factory -- Precision Biomarker Intelligence Agent v{VERSION}*",
            f"*Report generated {timestamp}. This report is for informational purposes and should "
            f"be reviewed by a qualified healthcare provider before making clinical decisions.*",
        ]
        return "\n".join(lines)

    # -- Section 1: Biological Age -----------------------------------------

    def _section_1_biological_age(self, analysis: AnalysisResult) -> str:
        ba = analysis.biological_age
        lines = [
            "## 1. Biological Age Assessment",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Chronological Age | {ba.chronological_age} years |",
            f"| Biological Age (PhenoAge) | {ba.biological_age:.1f} years |",
            f"| Age Acceleration | {ba.age_acceleration:+.1f} years |",
        ]
        if ba.grimage_score is not None:
            lines.append(f"| GrimAge Surrogate Score | {ba.grimage_score:.1f} years |")
        lines.append(f"| Mortality Risk Score | {ba.mortality_risk:.4f} |")

        # Confidence interval display
        ci = ba.confidence_interval if ba.confidence_interval else None
        if ci:
            lines.append(
                f"| 95% Confidence Interval | {ci.get('lower', '?')} - {ci.get('upper', '?')} years |"
            )
            lines.append(f"| Data Completeness | {ci.get('note', 'N/A')} |")
        if ba.risk_confidence:
            lines.append(f"| Risk Assessment Confidence | {ba.risk_confidence} |")
        lines.append("")

        # Interpretation
        if ba.age_acceleration > 5:
            lines.append(
                "**Interpretation:** Significantly accelerated aging detected. "
                "Biological age exceeds chronological age by more than 5 years, "
                "indicating elevated all-cause mortality risk and potential for "
                "age-related disease."
            )
        elif ba.age_acceleration > 2:
            lines.append(
                "**Interpretation:** Moderately accelerated aging. Targeted interventions "
                "on modifiable PhenoAge drivers (glucose, inflammation, RDW) are recommended."
            )
        elif ba.age_acceleration > -2:
            lines.append(
                "**Interpretation:** Biological age is within normal range of chronological age. "
                "Continue current health maintenance."
            )
        else:
            lines.append(
                "**Interpretation:** Biological age is younger than chronological age, indicating "
                "favorable metabolic resilience and slower aging trajectory."
            )

        # Top aging drivers
        if ba.aging_drivers:
            lines.append("")
            lines.append("**Top Aging Drivers:**")
            lines.append("")
            lines.append("| Biomarker | Value | Direction | Contribution |")
            lines.append("|-----------|-------|-----------|--------------|")
            for driver in ba.aging_drivers[:5]:
                lines.append(
                    f"| {driver.get('biomarker', '')} | "
                    f"{driver.get('value', '')} | "
                    f"{driver.get('direction', '')} | "
                    f"{driver.get('contribution', 0):.4f} |"
                )

        return "\n".join(lines)

    # -- Section 2: Executive Findings -------------------------------------

    def _section_2_executive_findings(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 2. Executive Findings",
            "",
            "**Top priority findings requiring attention:**",
            "",
        ]

        findings = []

        # Critical alerts first
        for alert in analysis.critical_alerts:
            findings.append(("CRITICAL", alert))

        # High-risk disease trajectories
        for traj in analysis.disease_trajectories:
            if traj.risk_level == RiskLevel.HIGH:
                findings.append((
                    "HIGH",
                    f"{traj.disease.value}: {traj.risk_level.value} risk. "
                    + (f"Estimated {traj.years_to_onset_estimate:.0f} years to onset. "
                       if traj.years_to_onset_estimate else "")
                    + f"Interventions: {', '.join(traj.intervention_recommendations[:2])}"
                    if traj.intervention_recommendations else "",
                ))
            elif traj.risk_level == RiskLevel.MODERATE:
                findings.append((
                    "MODERATE",
                    f"{traj.disease.value}: {traj.risk_level.value} risk. "
                    + (f"Monitoring recommended. "
                       f"Interventions: {', '.join(traj.intervention_recommendations[:2])}"
                       if traj.intervention_recommendations else "Monitoring recommended."),
                ))

        # Biological age finding
        if analysis.biological_age.age_acceleration > 2:
            findings.append((
                "HIGH",
                f"Biological age acceleration of {analysis.biological_age.age_acceleration:+.1f} years "
                f"detected. Multi-system aging intervention recommended.",
            ))

        # Sort by priority and take top 5
        priority_order = {"CRITICAL": 0, "HIGH": 1, "MODERATE": 2}
        findings.sort(key=lambda f: priority_order.get(f[0], 3))

        for i, (level, desc) in enumerate(findings[:5], 1):
            emoji_map = {"CRITICAL": "[!!!]", "HIGH": "[!!]", "MODERATE": "[!]"}
            marker = emoji_map.get(level, "[-]")
            lines.append(f"{i}. **{marker} {level}:** {desc}")

        if not findings:
            lines.append("No critical or high-priority findings detected.")

        return "\n".join(lines)

    # -- Section 3: Biomarker-Gene Correlation Map -------------------------

    def _section_3_biomarker_gene_map(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 3. Biomarker-Gene Correlation Map",
            "",
        ]

        if not analysis.genotype_adjustments:
            lines.append("No genotype-biomarker adjustments available for this patient.")
            return "\n".join(lines)

        lines.extend([
            "| Biomarker | Gene | Genotype | Standard Range | Adjusted Range | Rationale |",
            "|-----------|------|----------|----------------|----------------|-----------|",
        ])

        for adj in analysis.genotype_adjustments:
            rationale_short = adj.rationale[:150] + "..." if len(adj.rationale) > 150 else adj.rationale
            lines.append(
                f"| {adj.biomarker} | {adj.gene} | {adj.genotype} | "
                f"{adj.standard_range} | {adj.adjusted_range} | {rationale_short} |"
            )

        return "\n".join(lines)

    # -- Section 4: Disease Trajectories -----------------------------------

    def _section_4_disease_trajectories(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 4. Disease Trajectory Analysis",
            "",
        ]

        if not analysis.disease_trajectories:
            lines.append("No disease trajectory data available.")
            return "\n".join(lines)

        for traj in analysis.disease_trajectories:
            risk_indicator = {
                RiskLevel.CRITICAL: "[!!!]",
                RiskLevel.HIGH: "[!!]",
                RiskLevel.MODERATE: "[!]",
                RiskLevel.LOW: "[-]",
                RiskLevel.NORMAL: "[OK]",
            }.get(traj.risk_level, "[-]")

            lines.append(f"### {traj.disease.value.title()} {risk_indicator}")
            lines.append("")
            lines.append(f"**Risk Level:** {traj.risk_level.value}")

            if traj.years_to_onset_estimate:
                lines.append(
                    f"**Estimated Years to Clinical Onset:** ~{traj.years_to_onset_estimate:.0f} years"
                )

            if traj.current_markers:
                lines.append("")
                lines.append("**Current Biomarkers:**")
                for marker, value in traj.current_markers.items():
                    lines.append(f"- {marker}: {value}")

            if traj.genetic_risk_factors:
                lines.append("")
                lines.append("**Genetic Risk Factors:**")
                for factor in traj.genetic_risk_factors:
                    lines.append(f"- {factor}")

            if traj.intervention_recommendations:
                lines.append("")
                lines.append("**Recommended Interventions:**")
                for rec in traj.intervention_recommendations:
                    lines.append(f"- {rec}")

            lines.append("")

        return "\n".join(lines)

    # -- Section 5: Pharmacogenomic Profile --------------------------------

    def _section_5_pharmacogenomic_profile(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 5. Pharmacogenomic Profile",
            "",
        ]

        if not analysis.pgx_results:
            lines.append("No pharmacogenomic data available for this patient.")
            return "\n".join(lines)

        lines.extend([
            "| Gene | Star Alleles | Phenotype | Alert Level |",
            "|------|-------------|-----------|-------------|",
        ])

        alert_genes = []
        for pgx in analysis.pgx_results:
            phenotype = pgx.phenotype.value.replace("_", " ").title()
            alert = "Standard"
            if pgx.phenotype.value in ("poor", "ultra_rapid"):
                alert = "HIGH"
                alert_genes.append(pgx)
            elif pgx.phenotype.value == "intermediate":
                alert = "MODERATE"
            lines.append(
                f"| {pgx.gene} | {pgx.star_alleles} | {phenotype} | {alert} |"
            )

        # Detailed drug recommendations for alert-level genes
        if alert_genes:
            lines.append("")
            lines.append("### Drug-Specific Recommendations")
            lines.append("")
            for pgx in alert_genes:
                lines.append(f"**{pgx.gene} ({pgx.star_alleles} -- {pgx.phenotype.value})**")
                lines.append("")
                for drug_info in pgx.drugs_affected:
                    drug = drug_info.get("drug", "Unknown")
                    rec = drug_info.get("recommendation", "")
                    cpic = drug_info.get("cpic_level", "")
                    lines.append(f"- **{drug}** (CPIC {cpic}): {rec}")
                lines.append("")

        return "\n".join(lines)

    # -- Section 6: Nutritional Analysis -----------------------------------

    def _section_6_nutritional_analysis(self, analysis: AnalysisResult,
                                         profile: PatientProfile) -> str:
        lines = [
            "## 6. Nutritional Genomics Analysis",
            "",
        ]

        # Extract nutritional biomarkers and genotypes
        nutritional_markers = {}
        nutritional_genes = {
            "rs1801133": "MTHFR C677T",
            "rs174537": "FADS1",
            "rs2228570": "VDR FokI",
            "rs602662": "FUT2",
            "rs7501331": "BCMO1",
        }

        relevant_genotypes = {}
        for rs_id, gene_name in nutritional_genes.items():
            if rs_id in profile.genotypes:
                relevant_genotypes[gene_name] = profile.genotypes[rs_id]

        # Nutritional biomarkers
        nutrition_keys = [
            "vitamin_D_25OH", "folate_serum", "vitamin_b12", "omega3_index",
            "methylmalonic_acid", "homocysteine",
        ]
        for key in nutrition_keys:
            if key in profile.biomarkers:
                nutritional_markers[key] = profile.biomarkers[key]

        if not relevant_genotypes and not nutritional_markers:
            lines.append("No nutritional genomics data available for this patient.")
            return "\n".join(lines)

        if relevant_genotypes:
            lines.append("### Nutrigenetic Profile")
            lines.append("")
            lines.append("| Gene Variant | Genotype | Implication |")
            lines.append("|-------------|----------|-------------|")
            implications = {
                "MTHFR C677T": {
                    "CT": "Heterozygous; ~30% reduced enzyme activity. Consider methylfolate.",
                    "TT": "Homozygous; ~70% reduced activity. Methylfolate required, avoid folic acid.",
                    "CC": "Wild-type; standard folate metabolism.",
                },
                "FADS1": {
                    "GT": "Heterozygous; moderately reduced ALA-to-EPA/DHA conversion.",
                    "TT": "Homozygous; significantly reduced conversion. Preformed EPA/DHA needed.",
                    "GG": "Wild-type; standard fatty acid conversion.",
                },
                "VDR FokI": {
                    "CT": "Heterozygous; mildly reduced VDR function.",
                    "TT": "Homozygous; reduced VDR function. Higher vitamin D doses may be needed.",
                    "CC": "Wild-type; standard vitamin D receptor function.",
                },
                "FUT2": {
                    "AG": "Heterozygous; partial secretor status.",
                    "AA": "Non-secretor; reduced B12 absorption. Sublingual B12 preferred.",
                    "GG": "Secretor; standard B12 absorption.",
                },
                "BCMO1": {
                    "CT": "Heterozygous; moderately reduced beta-carotene conversion.",
                    "TT": "Homozygous; poor beta-carotene converter. Preformed vitamin A needed.",
                    "CC": "Wild-type; standard beta-carotene conversion.",
                },
            }
            for gene_name, genotype in relevant_genotypes.items():
                implication = implications.get(gene_name, {}).get(
                    genotype, "Genotype interpretation not available."
                )
                lines.append(f"| {gene_name} | {genotype} | {implication} |")

        if nutritional_markers:
            lines.append("")
            lines.append("### Current Nutritional Biomarkers")
            lines.append("")
            lines.append("| Biomarker | Value | Status |")
            lines.append("|-----------|-------|--------|")
            status_map = {
                "vitamin_D_25OH": lambda v: "Deficient" if v < 20 else ("Insufficient" if v < 30 else "Optimal"),
                "folate_serum": lambda v: "Deficient" if v < 3 else "Normal",
                "vitamin_b12": lambda v: "Deficient" if v < 200 else ("Borderline" if v < 300 else "Normal"),
                "omega3_index": lambda v: "High Risk" if v < 4 else ("Moderate Risk" if v < 8 else "Optimal"),
                "homocysteine": lambda v: "Elevated" if v > 15 else "Normal",
                "methylmalonic_acid": lambda v: "Elevated" if v > 270 else "Normal",
            }
            for marker, value in nutritional_markers.items():
                status_fn = status_map.get(marker, lambda v: "N/A")
                status = status_fn(value)
                lines.append(f"| {marker} | {value} | {status} |")

        return "\n".join(lines)

    # -- Section 7: Interconnected Pathways --------------------------------

    def _section_7_interconnected_pathways(self, analysis: AnalysisResult) -> str:
        # NOTE: Pathway connections are currently hardcoded based on known
        # cross-domain interactions. In future versions these should be
        # driven dynamically from the knowledge graph, allowing new pathway
        # links to be discovered as the graph is enriched with clinical
        # evidence and patient data.
        lines = [
            "## 7. Interconnected Pathways",
            "",
            "The following cross-domain connections were identified:",
            "",
        ]

        connections = []

        # Check for inflammation-aging connection
        ba = analysis.biological_age
        has_inflammation = any(
            d.get("biomarker") in ("ln_crp", "wbc", "rdw")
            and d.get("direction") == "aging"
            for d in ba.aging_drivers
        )
        if has_inflammation and ba.age_acceleration > 2:
            connections.append(
                "**Inflammation -> Accelerated Aging:** Elevated inflammatory markers "
                "(CRP, WBC, RDW) are driving biological age acceleration. These same "
                "markers are linked to cardiovascular and metabolic disease risk."
            )

        # Check for metabolic-liver connection
        diabetes_risk = any(
            t.disease.value == "diabetes" and t.risk_level in (RiskLevel.HIGH, RiskLevel.MODERATE)
            for t in analysis.disease_trajectories
        )
        liver_risk = any(
            t.disease.value == "liver" and t.risk_level in (RiskLevel.HIGH, RiskLevel.MODERATE)
            for t in analysis.disease_trajectories
        )
        if diabetes_risk and liver_risk:
            connections.append(
                "**Metabolic Syndrome -> NAFLD:** Insulin resistance and pre-diabetic trajectory "
                "are interconnected with liver disease risk. Addressing insulin sensitivity "
                "will benefit both metabolic and hepatic outcomes."
            )

        # Check for nutrition-methylation connection
        has_mthfr = "rs1801133" in analysis.patient_profile.genotypes
        has_homocysteine = "homocysteine" in analysis.patient_profile.biomarkers
        if has_mthfr and has_homocysteine:
            connections.append(
                "**MTHFR -> Methylation -> Cardiovascular:** MTHFR genotype affects "
                "homocysteine metabolism, which directly impacts cardiovascular risk "
                "and biological aging. Methylfolate supplementation addresses this pathway."
            )

        # PGx-disease interactions
        if analysis.pgx_results and analysis.disease_trajectories:
            connections.append(
                "**Pharmacogenomics -> Treatment Selection:** PGx profile must be considered "
                "when selecting medications for any identified disease trajectories. "
                "Metabolizer status affects drug efficacy and safety."
            )

        # Check for thyroid-cardiovascular connection
        thyroid_risk = any(
            t.disease.value == "thyroid" and t.risk_level in (RiskLevel.HIGH, RiskLevel.MODERATE)
            for t in analysis.disease_trajectories
        )
        cardio_risk = any(
            t.disease.value == "cardiovascular" and t.risk_level in (RiskLevel.HIGH, RiskLevel.MODERATE)
            for t in analysis.disease_trajectories
        )
        if thyroid_risk and cardio_risk:
            connections.append(
                "**Thyroid <-> Cardiovascular:** TSH abnormalities directly affect lipid "
                "metabolism. Subclinical hypothyroidism elevates LDL-C and triglycerides. "
                "Optimizing thyroid function may improve cardiovascular lipid profile."
            )

        # Check for iron-liver connection
        iron_risk = any(
            t.disease.value == "iron" and t.risk_level in (RiskLevel.HIGH, RiskLevel.MODERATE)
            for t in analysis.disease_trajectories
        )
        if iron_risk and liver_risk:
            connections.append(
                "**Iron <-> Liver:** Iron overload causes hepatic damage through oxidative "
                "stress and can accelerate fibrosis progression. Ferritin and transferrin "
                "saturation should be monitored alongside liver function markers."
            )

        if connections:
            for i, conn in enumerate(connections, 1):
                lines.append(f"{i}. {conn}")
                lines.append("")
        else:
            lines.append("No significant cross-domain pathway connections identified.")

        return "\n".join(lines)

    # -- Section 8: Action Plan --------------------------------------------

    def _section_8_action_plan(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 8. Prioritized Action Plan",
            "",
        ]

        actions = []

        # Critical PGx actions
        for alert in analysis.critical_alerts:
            if "PGx" in alert or "DPYD" in alert:
                actions.append(("IMMEDIATE", alert))

        # High-risk disease interventions
        for traj in analysis.disease_trajectories:
            if traj.risk_level in (RiskLevel.CRITICAL, RiskLevel.HIGH):
                for rec in traj.intervention_recommendations[:2]:
                    actions.append(("WITHIN 30 DAYS", f"{traj.disease.value}: {rec}"))

        # Biological age interventions
        if analysis.biological_age.age_acceleration > 3:
            actions.append((
                "WITHIN 30 DAYS",
                "Address top PhenoAge aging drivers through targeted interventions "
                "(glucose optimization, anti-inflammatory diet, exercise program)."
            ))

        # Moderate-risk interventions
        for traj in analysis.disease_trajectories:
            if traj.risk_level == RiskLevel.MODERATE:
                for rec in traj.intervention_recommendations[:1]:
                    actions.append(("WITHIN 90 DAYS", f"{traj.disease.value}: {rec}"))

        # Genotype-guided supplementation
        if analysis.genotype_adjustments:
            actions.append((
                "WITHIN 90 DAYS",
                "Implement genotype-guided supplementation protocol (see Section 10)."
            ))

        if actions:
            lines.append("| Priority | Timeline | Action |")
            lines.append("|----------|----------|--------|")
            for i, (timeline, action) in enumerate(actions[:10], 1):
                lines.append(f"| {i} | {timeline} | {action} |")
        else:
            lines.append("No urgent actions identified. Recommended baseline actions:")
            lines.append("")
            lines.append("1. Continue routine annual bloodwork (CBC, CMP, lipid panel)")
            lines.append("2. Maintain current exercise and dietary habits")
            lines.append("3. Recheck PhenoAge biomarkers in 6-12 months")

        return "\n".join(lines)

    # -- Section 9: Monitoring Schedule ------------------------------------

    def _section_9_monitoring_schedule(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 9. Monitoring Schedule",
            "",
            "| Test Panel | Frequency | Rationale |",
            "|-----------|-----------|-----------|",
        ]

        # Always recommend PhenoAge recheck
        lines.append(
            "| PhenoAge Panel (CBC, CMP, CRP) | Every 6 months | "
            "Track biological age trajectory and intervention response |"
        )

        # Disease-specific monitoring
        for traj in analysis.disease_trajectories:
            if traj.risk_level in (RiskLevel.HIGH, RiskLevel.CRITICAL):
                freq = "Every 3 months"
            elif traj.risk_level == RiskLevel.MODERATE:
                freq = "Every 6 months"
            else:
                continue

            disease_panels = {
                "diabetes": "HbA1c, fasting glucose, fasting insulin, HOMA-IR",
                "cardiovascular": "Lipid panel, Lp(a), ApoB, hs-CRP",
                "liver": "ALT, AST, GGT, FIB-4 calculation, ferritin",
                "thyroid": "TSH, free T4, free T3, anti-TPO",
                "iron": "Ferritin, transferrin saturation, serum iron, TIBC",
                "nutritional": "Vitamin D, folate, B12, omega-3 index, homocysteine",
            }
            panel = disease_panels.get(traj.disease.value, "Standard panel")
            lines.append(
                f"| {traj.disease.value.title()} Panel ({panel}) | {freq} | "
                f"{traj.risk_level.value} risk -- active monitoring |"
            )

        # PGx follow-up
        if analysis.pgx_results:
            lines.append(
                "| PGx review | With each new medication | "
                "Verify new prescriptions against PGx profile |"
            )

        return "\n".join(lines)

    # -- Section 10: Supplement Protocol -----------------------------------

    def _section_10_supplement_protocol(self, analysis: AnalysisResult,
                                         profile: PatientProfile) -> str:
        lines = [
            "## 10. Supplement Protocol Summary",
            "",
            "*Genotype-guided supplementation recommendations. Discuss with healthcare provider.*",
            "",
            "| Supplement | Form | Dose | Genotype Basis | Rationale |",
            "|-----------|------|------|----------------|-----------|",
        ]

        genotypes = profile.genotypes
        # Normalize genotype keys: support both "rs1801133" and "MTHFR_rs1801133" formats
        normalized = {}
        for key, val in genotypes.items():
            normalized[key] = val
            # Extract rsID from compound keys like "MTHFR_rs1801133"
            if "_rs" in key:
                rs_id = key.split("_rs", 1)[1]
                normalized[f"rs{rs_id}"] = val
        genotypes = normalized
        supplements = []

        # MTHFR-guided folate
        mthfr_gt = genotypes.get("rs1801133", "")
        if mthfr_gt in ("CT", "TT"):
            dose = "400-800 mcg/day" if mthfr_gt == "CT" else "800-1000 mcg/day"
            supplements.append((
                "Folate", "L-Methylfolate (5-MTHF)", dose,
                f"MTHFR C677T {mthfr_gt}",
                "Bypass impaired MTHFR enzyme; avoid synthetic folic acid",
            ))

        # FADS1-guided omega-3
        fads_gt = genotypes.get("rs174537", "")
        if fads_gt in ("GT", "TT"):
            dose = "2-3 g/day" if fads_gt == "GT" else "3-4 g/day"
            supplements.append((
                "Omega-3", "Preformed EPA/DHA (fish oil)", dose,
                f"FADS1 {fads_gt}",
                "Reduced ALA-to-EPA/DHA conversion; need preformed long-chain omega-3",
            ))

        # VDR-guided vitamin D
        vdr_gt = genotypes.get("rs2228570", "")
        if vdr_gt in ("CT", "TT"):
            dose = "2000-4000 IU/day" if vdr_gt == "CT" else "4000-5000 IU/day"
            supplements.append((
                "Vitamin D3", "Cholecalciferol", dose,
                f"VDR FokI {vdr_gt}",
                "Reduced VDR function; target 25(OH)D > 40 ng/mL",
            ))

        # FUT2-guided B12
        fut2_gt = genotypes.get("rs602662", "")
        if fut2_gt in ("AG", "AA"):
            supplements.append((
                "Vitamin B12", "Methylcobalamin (sublingual)", "1000-2000 mcg/day",
                f"FUT2 {fut2_gt}",
                "Non-secretor or partial; reduced oral B12 absorption",
            ))

        # BCMO1-guided vitamin A
        bcmo1_gt = genotypes.get("rs7501331", "")
        if bcmo1_gt in ("CT", "TT"):
            supplements.append((
                "Vitamin A", "Retinol (preformed)", "2500-5000 IU/day",
                f"BCMO1 {bcmo1_gt}",
                "Poor beta-carotene converter; need preformed retinol",
            ))

        # DIO2-guided selenium (thyroid support)
        dio2_gt = genotypes.get("rs225014", "")
        if dio2_gt in ("GA", "AA"):
            supplements.append((
                "Selenium", "Selenomethionine", "200 mcg/day",
                f"DIO2 Thr92Ala {dio2_gt}",
                "Support T4-to-T3 conversion; cofactor for deiodinase enzymes",
            ))

        if supplements:
            for supp in supplements:
                lines.append(f"| {supp[0]} | {supp[1]} | {supp[2]} | {supp[3]} | {supp[4]} |")
        else:
            lines.append(
                "| -- | -- | -- | -- | "
                "No genotype-specific supplementation adjustments identified |"
            )

        return "\n".join(lines)

    # -- Section 11: Clinical Summary for MD -------------------------------

    def _section_11_clinical_summary(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 11. Clinical Summary for Healthcare Provider",
            "",
        ]

        profile = analysis.patient_profile
        ba = analysis.biological_age

        lines.append(
            f"**Patient:** {profile.patient_id}, {profile.age}yo {profile.sex}"
        )
        lines.append(
            f"**Biological Age:** {ba.biological_age:.1f} years "
            f"(acceleration: {ba.age_acceleration:+.1f} years)"
        )
        lines.append("")

        # Key findings summary
        lines.append("**Key Findings:**")
        lines.append("")

        # Critical alerts
        if analysis.critical_alerts:
            for alert in analysis.critical_alerts:
                lines.append(f"- {alert}")
            lines.append("")

        # Disease risks
        risk_diseases = [
            t for t in analysis.disease_trajectories
            if t.risk_level in (RiskLevel.HIGH, RiskLevel.MODERATE, RiskLevel.CRITICAL)
        ]
        if risk_diseases:
            lines.append("**Elevated Disease Risks:**")
            for traj in risk_diseases:
                lines.append(
                    f"- {traj.disease.value}: {traj.risk_level.value}"
                    + (f" (est. {traj.years_to_onset_estimate:.0f}y to onset)"
                       if traj.years_to_onset_estimate else "")
                )
            lines.append("")

        # PGx alerts
        alert_pgx = [
            p for p in analysis.pgx_results
            if p.phenotype.value in ("poor", "ultra_rapid")
        ]
        if alert_pgx:
            lines.append("**Pharmacogenomic Alerts:**")
            for pgx in alert_pgx:
                lines.append(
                    f"- {pgx.gene} {pgx.star_alleles}: {pgx.phenotype.value} metabolizer"
                )
            lines.append("")

        # Recommended actions
        lines.append("**Recommended Actions:**")
        lines.append("1. Review critical alerts and PGx findings")
        lines.append("2. Implement prioritized interventions (Section 8)")
        lines.append("3. Order follow-up labs per monitoring schedule (Section 9)")
        lines.append("4. Discuss supplement protocol with patient (Section 10)")

        return "\n".join(lines)

    # -- Section 12: References --------------------------------------------

    def _section_12_references(self) -> str:
        return (
            "## 12. References\n\n"
            "1. Levine ME et al. An epigenetic biomarker of aging for lifespan and healthspan. "
            "*Aging (Albany NY)*. 2018;10(4):573-591.\n"
            "2. Lu AT et al. DNA methylation GrimAge strongly predicts lifespan and healthspan. "
            "*Aging (Albany NY)*. 2019;11(2):303-327.\n"
            "3. Relling MV, Klein TE. CPIC: Clinical Pharmacogenetics Implementation Consortium "
            "of the Pharmacogenomics Research Network. *Clin Pharmacol Ther*. 2011;89(3):464-467.\n"
            "4. Romeo S et al. Genetic variation in PNPLA3 confers susceptibility to nonalcoholic "
            "fatty liver disease. *Nat Genet*. 2008;40(12):1461-1465.\n"
            "5. Frosst P et al. A candidate genetic risk factor for vascular disease: a common "
            "mutation in methylenetetrahydrofolate reductase. *Nat Genet*. 1995;10(1):111-113.\n"
            "6. PharmGKB / CPIC Guidelines. https://cpicpgx.org/guidelines/\n"
            "7. ClinVar database. https://www.ncbi.nlm.nih.gov/clinvar/\n"
            "8. Nordestgaard BG et al. Lipoprotein(a) as a cardiovascular risk factor. "
            "*Eur Heart J*. 2010;31(23):2844-2853.\n"
            "9. European Association for the Study of the Liver. EASL Clinical Practice Guidelines "
            "on non-invasive tests for evaluation of liver disease severity and prognosis. "
            "*J Hepatol*. 2021;75(3):659-689.\n"
            "10. Tanaka T et al. Genome-wide association study of vitamin B6, vitamin B12, folate, "
            "and homocysteine blood concentrations. *Am J Hum Genet*. 2009;84(4):477-482."
        )

    # -- Section 13: Clinical Validation & Limitations ---------------------

    def _section_13_clinical_validation(self, analysis: AnalysisResult) -> str:
        lines = [
            "## 13. Clinical Validation & Limitations",
            "",
            "This analysis uses the following validated algorithms:",
            "",
            "| Algorithm | Validation Cohort | Citation |",
            "| --- | --- | --- |",
            "| PhenoAge | NHANES III (n=11,432) | Levine et al. 2018 PMID:29676998 |",
            "| GrimAge Surrogate | Plasma protein proxies | Lu et al. 2019 PMID:30669119 |",
            "| CPIC PGx Guidelines | Multi-ethnic clinical trials | CPIC (cpicpgx.org) |",
            "| Disease Trajectories | ADA/ESC/AASLD guidelines | See per-section citations |",
            "",
            "**Important limitations:**",
            "",
        ]

        # Determine SE to display based on whether confidence_interval data is present
        se_value = 4.9
        if (analysis.biological_age.confidence_interval
                and "standard_error" in analysis.biological_age.confidence_interval):
            se_value = analysis.biological_age.confidence_interval["standard_error"]

        lines.append(
            "1. Reference ranges are based primarily on European-descent cohorts. "
            "Population-specific adjustments should be considered for non-European ancestries."
        )
        lines.append(
            "2. PhenoAge confidence interval is ±{:.1f} years (95% CI). ".format(se_value)
            + "Individual results may vary."
        )
        lines.append(
            "3. GrimAge surrogate uses plasma protein proxies, not methylation data. "
            "True GrimAge requires DNA methylation arrays."
        )
        lines.append(
            "4. Pharmacogenomic recommendations follow CPIC Level 1A guidelines only. "
            "Clinical context and concurrent medications must be considered."
        )
        lines.append(
            "5. This tool is for research and informational purposes. "
            "All findings should be validated by a qualified healthcare provider."
        )

        return "\n".join(lines)
